### ISSUE TITLE
Next.js Amplify Serverless AppSync graphql (Amplify error)

### ISSUE THREAD

**Issue by anupam-newgen** [danielcondemarin/serverless-next.js#110]
Hi, 
I'm trying to create an App that uses Amplify and AppSync with Next.js.

I was able to deploy the application successfully but when I'm trying to access the application (trying to fetch data from AppSync) It is failing. 

I'm kinda lost what needs to be looked at, the application seems to be working fine locally but when I'm publishing it on AWS it is failing.

I'm getting error: TypeError: Cannot read property 'getName' of undefined
//quotes.js
import { Connect } from 'aws-amplify-react';
........
<Connect
        query={graphqlOperation(queries.getName)}
        subscription={graphqlOperation(subscriptions.onCreateName)}
        onSubscriptionMsg={(prev, { onCreateName }) => ({
          ...prev,
          getName: {
            ...prev.getName,
            items: [
              ...prev.getName.items,
              onCreateName,
            ],
          },
        })}
      >
....
Please assist.

Thanks and Regards,

**Comment by romainquellec** [comment]
IMO, its not related to this plugin.
You can ask on https://github.com/awslabs/aws-mobile-appsync-sdk-js
