### ISSUE TITLE
Tips for improving latency

### ISSUE THREAD

**Issue by barrysteyn** [danielcondemarin/serverless-next.js#132]
Hi,

Please can we have some tips/ideas for improving latency. One of my sites, has the following stats:
```
         ---------Operation is beginning---------
      url_effective :  'https://sayy.it/sayy' <-- (The URL that was fetched last.)
          http_code :  200 <-- (The numerical response code that was found in the last retrieved HTTP(S) or FTP(s) transfer.)
       content_type :  'text/html; charset=utf-8' <-- (The Content-Type of the requested document, if there was any.)

         ---------Local DNS resolution beginning---------
    time_namelookup :  0.004911 <-- (The time, in seconds, it took from the start until the DNS name resolution was completed.)

         ---------Connection to CloudFront beginning---------
       time_connect :  0.012322 <-- (The time, in seconds, it took from the start until the TCP connect to the remote host (or proxy) was completed.)
    time_appconnect :  0.043697 <-- (The time, in seconds, it took from the start until the SSL/SSH/etc connect/handshake to the remote host was completed.)

         ---------Communication between CloudFront and API Gateway (via Internet backbone networks) beginning---------
   time_pretransfer :  0.043951 <-- (The time, in seconds, it took from the start until the file transfer was just about to begin.)
      time_redirect :  0.000000 <-- (The time, in seconds, it took for all redirection steps before the final transaction was started.)

         ---------NOTE: Communication between API Gateway and the Integration Request Endpoint occurring---------
         ---------NOTE: Communication between API Gateway and CloudFront (via Internet backbone networks) occurring---------

         ---------Response from CloudFront beginning---------
 time_starttransfer :  1.125288 <-- (The time, in seconds, it took from the start until the first byte was just about to be transferred.)
      size_download :  43629 <-- (The total amount of bytes that were downloaded.)

         ---------Response has been received---------
         time_total :  1.134074 <-- (The total time, in seconds, that the full operation lasted.)
         ---------Operation is complete---------
```

Look at the *time_starttransfer*, I have no idea how to decrease it. Note: The lambda is warm, and this page is static (i.e. no backend DB calls).

**Comment by danielcondemarin** [comment]
@barrysteyn I would recommend checking out the new component I've just released https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component. This new version has an improved architecture where the pages are rendered at the edge or if static fetched from S3. This results in very low latency times.

**Comment by barrysteyn** [comment]
@danielcondemarin This is amazing. Question: Can I provision resources as per usual in a serverless.yml file, or do I need to create specific JS logic to do this (like you have done in the example).

**Comment by danielcondemarin** [comment]
> @danielcondemarin This is amazing. Question: Can I provision resources as per usual in a serverless.yml file, or do I need to create specific JS logic to do this (like you have done in the example).

To provision other resources you can use (but not forced to) any other serverless component in this list: https://github.com/serverless-components/

**Comment by barrysteyn** [comment]
Right! But I think you can also the old `resources` for adding cloudformation manually?

**Comment by danielcondemarin** [comment]
@barrysteyn This serverless component provisions any cloudformation you pass to it: https://github.com/serverless-components/aws-cloudformation/blob/master/README.md

**Comment by barrysteyn** [comment]
Last question: What about all the plugins available for the old serverless
env. For example, the warmup plugin is an incredibly useful plugin. I
assume one can still use them?

**Comment by danielcondemarin** [comment]
> Last question: What about all the plugins available for the old serverless env. For example, the warmup plugin is an incredibly useful plugin. I assume one can still use them?
> […](#)

Currently, the plugins for the old serverless env. are incompatible with the new components release.
However, with the new next component arch. you don't have to worry about cold starts. All next pages are deployed to Lambda@Edge. The edge lambda will be invoked for any of your page requests which should keep it warm.

**Comment by barrysteyn** [comment]
@danielcondemarin Finally finding time to go through your examples. Question: In the dynamodb example, why didn't you use the dynamodb component to provision your table as opposed to doing it by hand?

**Comment by danielcondemarin** [comment]
@barrysteyn That’s ultimately the plan, however, the dynamo component doesn’t support global dynamo tables but I’m working on that atm. As soon as that lands I’ll update the example 🙂
