### ISSUE TITLE
Please Update the Readme to reflect NextJS v9

### ISSUE THREAD

**Issue by pkellner** [danielcondemarin/serverless-next.js#136]
It would be helpful to understand how this relates to the target serverless mode of NextJS v9 (if it does at all). I looked through the readme and there was no mention I could find of v9 and it seems that's very important when considering using this.

**Comment by ScorpIan555** [comment]
If you check issue #101 you'll see a discussion answering your question.  Currently the plugin targets v8 and (per that thread and my own experience) it's incompatible with v9

**Comment by ScorpIan555** [comment]
> @pkellner If you check issue #101 you'll see a discussion answering your question. Currently the plugin targets v8 and (per that thread and my own experience) it's incompatible with v9

Actually, I'm able to use it per the hack ref'd in that thread (call getInitialProps in the index page).  I can vouch for it in ever project, but I've got it working in mine right now.

**Comment by danielcondemarin** [comment]
The new component released now visible on the main README page supports next 9 🚀 
Closing this
