### ISSUE TITLE
Best way to add Cache-Control to assets?

### ISSUE THREAD

**Issue by mattdell** [danielcondemarin/serverless-next.js#139]
I'm going through Lighthouse recommendations and the only major thing left for me is to "Serve static assets with an efficient cache policy"

The recommendation here is to add a `Cache-Control: max-age=xxxxxxx` header.

Further reading here: https://developers.google.com/web/tools/lighthouse/audits/cache-policy?utm_source=lighthouse&utm_medium=cli

Do we need to update the s3 upload, api-gw-static.yml, or is there a more preferred way?

**Comment by barrysteyn** [comment]
@mattdell I have submitted a PR to get things going (see #40). However I suspect it is being ignored because it is applicable to the old plugin and not the new component.

**Comment by danielcondemarin** [comment]
@barrysteyn Sorry I’ve not had time to look into this, been quite busy with the component release. 
I’ll have a look today or tomorrow. However, I do recommend moving over to the new component as its effectively a new version (unfortunately breaking :()

**Comment by barrysteyn** [comment]
Yes, I intend to move over. But I need to support this version until I am able to migrate us there. Also, we have our backend in another repo and may not be able to combine the two that easily as is recommended by the new component.

**Comment by danielcondemarin** [comment]
Hi folks 👋 Now that https://github.com/danielcondemarin/serverless-next.js/pull/144 has been merged (thanks to @barrysteyn for implementing!) I'm closing this 🚀
