### ISSUE TITLE
[serverless-nextjs-component] can't get it to work

### ISSUE THREAD

**Issue by Zn4rK** [danielcondemarin/serverless-next.js#140]
I realize that this component is fairly new. You published it today. But I tried to utilize it in a project but I ran into this issue:

serverless.yml:
```
nextApp:
  component: "serverless-next.js"
```

```
  error:
  Error:   method deploy not found
    at Object.runComponents (/home/me/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:111:15)
```

**Comment by Zn4rK** [comment]
Okay - I ran "sls" instead of "sls deploy" and it seems to work a bit better. Sorry!

**Comment by danielcondemarin** [comment]
@Zn4rK What version of the serverless framework are you using?

**Comment by danielcondemarin** [comment]
> Okay - I ran "sls" instead of "sls deploy" and it seems to work a bit better. Sorry!

Oh I see :D No worries, let me know if you find any other issues.
