### ISSUE TITLE
unzipped size must be smaller - large next project 

### ISSUE THREAD

**Issue by jschimmoeller** [danielcondemarin/serverless-next.js#141]
recieved this error when trying to deploy 

 112s » nextApp » InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes

**Comment by danielcondemarin** [comment]
Sorry for the late reply @jschimmoeller .

Here is my idea to solve this problem:

1 - Create a separate cache behaviour for `/api` requests. 
This allows separating the deployment packages for /api pages and standard pages. API pages would have 50MB zipped up and standard pages another 50MB.
2 - If the above is not enough, we can detect this and create more granular cache behaviours with their own lambda function associations. For example, in your app 2 more cache behaviours could be created for `series/` and `watching/`. Again this frees up some space in the main Lambda allowing for bigger apps. 

I'm not very sure about 2. as it adds a lot of complexity to the project but 1. certainly makes a lot of sense.

**Comment by jschimmoeller** [comment]
@danielcondemarin 

My api directory as it is right now is 90mb.  The series and watch folder are dynamic routes which together are only 17mb.  The remaining pages are 147mb.  

Based on your input above I would need to be able to setup multiple "cache behavior" in order to get around what appears to be the 50MB limit. 

thanks
james

**Comment by danielcondemarin** [comment]
@jschimmoeller Are those numbers after zipping up?

**Comment by jschimmoeller** [comment]
@danielcondemarin sorry but no that is just based on the directory /files sizes

i used 7-zip and here are my values:

api folder - 16.6mb zipped
remaining pages - 31.2mb zipped

so based on your original reply it would be under 50mb

thanks
James

**Comment by danielcondemarin** [comment]
@jschimmoeller Just published `1.2.0-alpha.0` which should address this issue. 
I've added the `api/*` cache behaviour for api pages. Also, fixed an issue where HTML static pages where getting put in the lambda@edge src producing bigger packages unnecessarily. 
Let me know how it goes and feel free to re-open if you encounter any problems 👍

**Comment by jschimmoeller** [comment]
@danielcondemarin just updated package.json and did a deploy was able to deploy it 👍   I am currently tracking down a 500 :( I hope it is on my end

**Comment by danielcondemarin** [comment]
> @danielcondemarin just updated package.json and did a deploy was able to deploy it 👍 I am currently tracking down a 500 :( I hope it is on my end

Good stuff! Let me know if it isn't :)
