### ISSUE TITLE
Clearing stale pages from `.next/serverless/pages`

### ISSUE THREAD

**Issue by roberttaylor426** [danielcondemarin/serverless-next.js#143]
Apologies, this is probably a noobie question, but I was wondering what the best way for clearing stale pages from the `.next/serverless/pages` directory was?

Having deleted a page from the project `pages` directory, I was stuck for some time trying to figure out why `serverless offline` was still find my old page.

Am I supposed to clear the aforementioned cache dir periodically? Or is there a task for performing clean-up?

Thanks in advance.

**Comment by danielcondemarin** [comment]
@roberttaylor426 You can safely delete the `.next/` directory as it will be re-generated on each build. In future this might get done automatically by next as per https://github.com/zeit/next.js/issues/6009 :)
