### ISSUE TITLE
Component: domain not removed

### ISSUE THREAD

**Issue by josephluck** [danielcondemarin/serverless-next.js#150]
When running `serverless remove` from the CLI, any custom domain specified in `serverless.yml` is not removed. 

Looking in to the source code, it seems as though `@serverless/domain`'s `remove()` method is not called [(here's the code)](https://github.com/serverless-components/domain/blob/master/serverless.js#L183) in the serverless-next.js plugin's `remove()` method.

**Comment by danielcondemarin** [comment]
Good catch @josephluck !  Thanks for reporting 🙏 

Just published `@1.2.1-alpha.0` which fixes this.
