### ISSUE TITLE
Deploy with aws configure profile

### ISSUE THREAD

**Issue by cristiam86** [danielcondemarin/serverless-next.js#162]
How can I use an aws profile already configured? I have tried:
`serverless --profile myProfile`

and also in the serverless.yml file:
`provider:
  profile: myProfile`

But none seems to work.

**Comment by danielcondemarin** [comment]
The next component credentials can be configured as per https://github.com/serverless/components#credentials. 

tl;dr: You'll need a `.env` file with your access and secret key. Or exported env. variables.
