### ISSUE TITLE
Considering adding this Component to Serverless official templates?

### ISSUE THREAD

**Issue by Vadorequest** [danielcondemarin/serverless-next.js#167]
https://github.com/serverless/components/tree/master/templates

Would allow to get started much faster from an official boilerplate :)

**Comment by danielcondemarin** [comment]
@Vadorequest This definitely needs doing. Happy to take PRs on that if you have any spare time 🙏

**Comment by Vadorequest** [comment]
I don't have much spare time, but this project is of high interest to me so I may allocate some.

Currently, I believe the Next Component should live in its own repo and have its own documentation before considering releasing something "official", I fell it's still very early and doesn't match the quality of the Serverless plugin yet. So I'd rather recommend making it proper, achieve parity with the plugin and then releasing it as an official component.

I understand you want to keep both the plugin and the component, and that's maybe why you kept them both in the same repository? I see you've added labels to distinguish issues between both, that's a good idea! :)
