### ISSUE TITLE
Getting started - Troubleshooting

### ISSUE THREAD

**Issue by Vadorequest** [danielcondemarin/serverless-next.js#169]
Hi @danielcondemarin, thank you for this. I'm trying to get started with this serverless Component and I've got lots of questions for you. 😄 

- Do you consider using a dedicated repository for this Serverless Component (`serverless-next.js`)? Right now, I got lost in documentation and issues about whether they meant the plugin or the component. It's very confusing.
- Which branch should I use?`master`? Or [`serverless-component-v2`](https://github.com/danielcondemarin/serverless-next.js/tree/serverless-component-v2/packages/serverless-nextjs-component)? I saw you changed the component's name in the v2 branch `@serverless/nextjs` instead of `serverless-next.js`. 
- Could you update the "getting started" documentation? I had a really hard time getting something working on localhost. The README should definitely mention using the example https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component/examples/create-next-app when starting from scratch. (maybe I can make a PR?)
- Following the `create-next-app` example didn't deploy "anything" on AWS. How do I deploy a basic Next app to AWS? (it deployed something, but there are no endpoint to see the app online)

  Here is my deployment logs, I was expecting a link in the "endpoints" section:

  >Service Information
service: tfp
stage: development
region: eu-west-1
stack: tfp-development
resources: 1
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  None
Serverless: Invoke aws:deploy:finalize
Serverless: [AWS s3 200 0.141s 0 retries] listObjectsV2({ Bucket: 'tfp-development-serverlessdeploymentbucket-18gzf8i3lr0hf',
  Prefix: 'serverless/tfp/development' })
Serverless: Publishing service to the Serverless Dashboard...
Serverless: [AWS sts 200 0.368s 0 retries] getCallerIdentity({})
Serverless: [AWS cloudformation 200 0.139s 0 retries] describeStacks({ StackName: 'tfp-development' })
platform-sdk fetching: POST https://api.serverless.com/core/tenants/unlyed/applications/tfp/services/tfp/stages/development/regions/eu-west-1/deployments
Serverless: Successfully published your service to the Serverless Dashboard: https://dashboard.serverless.com/tenants/unlyed/applications/tfp/services/tfp/stage/development/region/eu-west-1
✨  Done in 7.10s.
- I'm considering using this plugin/component and helping out, I need to have a working setup kinda fast, could we talk more in private? (discord, slack, whatever?)

**Comment by danielcondemarin** [comment]
@Vadorequest thanks for the great questions. Hopefully I’ve addressed them all below:

- I did but it was much easier for to reuse all of the stuff I have in the mono-repo setup already for unit tests, libraries etc. Is not also reusability but also its easier to manage everything in one place for me such as PRs, issues etc. Over time I hope the distinction will be clearer between the component and the plugin. Also I can foresee the plugin dissapearing at some point in future.

- Use master. I never use any other branches for stable releases. The plan was to release the component under the @serverless org. but that wasn’t possible for a variety of reasons.

- Oh a PR would be much appreciated. I’ve been trying to add as much doc. as possible but I appreciate it may not be enough.

- Seems like you’re using the serverless framework v1 format with `provider`, `plugins` etc. Serverless components don’t work like this (at least for now). I’ve added a FAQ section about this here as it has come up a few times: https://github.com/danielcondemarin/serverless-next.js/blob/master/README.md#my-component-doesnt-deploy

-  Just ping me on slack at the serverless contrib channel @Dan 🙂
