### ISSUE TITLE
Redirecting routes cause 503 CloudFront error

### ISSUE THREAD

**Issue by zachabney** [danielcondemarin/serverless-next.js#174]
I'm trying to setup routes that redirect using the serverless component. I did this by creating a page that matches the path, similar to this: https://github.com/zeit/next.js/wiki/Redirecting-in-%60getInitialProps%60.

However, invoking the `res.end()` seems to cause a 503 error with CloudFront.

![image](https://user-images.githubusercontent.com/1711757/65842397-d0864680-e2f0-11e9-9c0c-fa111ee2633f.png)

Is there a better way to be handling redirects with serverless?

**Comment by janicduplessis** [comment]
Fixed in https://github.com/danielcondemarin/serverless-next.js/pull/176

**Comment by danielcondemarin** [comment]
Thanks for fixing this @janicduplessis ! It has now been published @1.2.4.
