### ISSUE TITLE
Cloudfront 503 ERROR

### ISSUE THREAD

**Issue by cristiam86** [danielcondemarin/serverless-next.js#181]
I'm getting a 503 error from CloudFront from my app deployed with this plugin. 
The error seems to occur when a page takes longer than 10 seconds to respond. I have already increased the limit of the lambda and invalidated CloudFront cache, but it still happens.
Since we are catching the response of the API queried to obtain the data needed to show the page, if the user refreshes the page, the page gets showed without an error.

You can try it out at: https://data.enantio.com with any random search. If the result page is showed instantly, then try for a different search because that one would be cached for sure.

Here is my response header
```content-length: 1217
content-type: text/html
date: Wed, 02 Oct 2019 12:40:25 GMT
server: CloudFront
status: 503
via: 1.1 9b51ea0192df87ecb2185cd2247e4a1b.cloudfront.net (CloudFront)
x-amz-cf-id: S4ARsV1e_Oj6NX-eZJAeb8RKadcruVN_Fd8UHHkUgmkidL7SCLFMZg==
x-amz-cf-pop: MAD51-C1
x-cache: LambdaExecutionError from cloudfront
```

And the message obtained from CloudFront:
```
503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions.
If you received this error while trying to use an app or access a website, please contact the provider or website owner for assistance.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by following steps in the CloudFront documentation (http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-503-service-unavailable.html).
Generated by cloudfront (CloudFront)
Request ID: 0X8O19E4s2kbWJSgrZ7I0zAI0sXHqhNdJ6e0Njq93JUVreeHSWl8Fg==
```

**Comment by danielcondemarin** [comment]
@cristiam86 Could you post your Lambda CloudWatch logs as well? You can find these in the CloudWatch service page. Also, make sure you look at the right region where your Lambda executed:

![image](https://user-images.githubusercontent.com/1122442/66310006-f6b87180-e902-11e9-8461-b52cd39bbd8f.png)

**Comment by cristiam86** [comment]
Sure @danielcondemarin Thanks!

This is an error record
<img width="1331" alt="Screenshot 2019-10-07 at 14 19 59" src="https://user-images.githubusercontent.com/4550355/66311083-ec4fa500-e90d-11e9-8b0b-fbbaf00379ed.png">

And this is a successful record
<img width="1272" alt="Screenshot 2019-10-07 at 14 20 05" src="https://user-images.githubusercontent.com/4550355/66311098-f5d90d00-e90d-11e9-8804-2ed3a9b484d7.png">

Also the lambda timeout is increased to 30 seconds but the error persists.

Regarding the regions configuration, I see that the lambda is deployed on us-east-1 but the logs are getting recorded on London (I've verified this refreshing the page and seeing more logs added to CloudWatch). Is there a way to deploy the Lamda to a specific region?

**Comment by danielcondemarin** [comment]
Do you know or suspect what might be causing the timeout? i.e. outbound network request issued from the Lambda?

The master lambda is in us-east-1, but is replicated globally to many regions so it can't be deployed to one specific region. This is by design 🙂

**Comment by cristiam86** [comment]
The website calls a serverless API (https://rctf69ejt3.execute-api.eu-central-1.amazonaws.com/prod/data?flow=imp&product=220410&reporter=251&partner=all) that may take longer than 10 seconds depending on the parameters and catching policies.

About the master lambda region, perfect, I understand.

**Comment by cristiam86** [comment]
Hello @danielcondemarin if there is something I can help with in order to solve this issue please just let me know.

**Comment by danielcondemarin** [comment]
@cristiam86 This is happening because the default timeout for the Lambda is 10 seconds. I believe it could be increased to 30 seconds. However, I don't think it is a good idea to increase it because this blocks the page load which is really poor ux.  

I would suggest you gracefully handle timeouts with a value lower than seconds. A few examples of how to do that using fetch [here](https://stackoverflow.com/questions/46946380/fetch-api-request-timeout). If it times out (maybe after 5 secs) defer the API call to the client. 

I don't think there is anything else the component can do here to help. Is that fair?

**Comment by cristiam86** [comment]
hey @danielcondemarin thanks for the response. The problem here is that when the query is not catched it depends on a 3rd party API and we can't improve its performance. Also the SSR is key  for SEO purposes so deferring the call to client wouldn't work for us. 
Also, I increased the timeout for the lambda to 30 seconds on the AWS console but it seems to don't have any effect. If you can just point out where to change this limit it would be awesome.

**Comment by danielcondemarin** [comment]
@cristiam86 The timeout can be reflected in the Console here:

![image](https://user-images.githubusercontent.com/1122442/66505004-5c069100-eac2-11e9-98b8-2850d240c2f9.png)

You might have to publish a new version of the Lambda for this to work but to be honest, I don't know if it will get overridden by the component on subsequent deployments

You could add a cache layer in front of the third party service and cache popular requests. In my opinion increasing the timeout to 30 seconds won't solve much, I'd be surprised if users stick around that much waiting for the page load.

**Comment by cristiam86** [comment]
@danielcondemarin like I said in my first post, I have already increased the limit to 30 seconds but the error persists. Here is my configuration:
<img width="753" alt="Screenshot 2019-10-09 at 19 40 23" src="https://user-images.githubusercontent.com/4550355/66506043-dcca8a80-eacc-11e9-92dd-056ca4ccb91c.png">

Also I have already implemented a cache layer in front of the 3rd party service to cache popular requests so I don't care if one query takes 30 seconds to one user since it's going to be fast to next users. The 503 error pushes away more users than a 30 seconds waiting time.

**Comment by danielcondemarin** [comment]
@cristiam86 Did you also publish a new version of the function? 

![image](https://user-images.githubusercontent.com/1122442/66508247-97a45980-eac8-11e9-94e8-a6c531bbc3bd.png)

Also the new published version would have to be updated in the CloudFront Cache Behaviour (example is set to 23):

![image](https://user-images.githubusercontent.com/1122442/66508320-cc181580-eac8-11e9-9680-8934da958ebf.png)

**Comment by danielcondemarin** [comment]
@cristiam86 Manually increasing the timeout like that is probably not going to play nice with the component deployments. 
I'm happy to accept a PR to pass a custom timeout for the Lambda functions, which defaults to 10 seconds. 

Something like:

```yml
myNextApp:
  component: "serverless-next.js"
  inputs:
    timeout: 30s
```

Could you verify first setting the 30seconds manually works?

**Comment by cristiam86** [comment]
@danielcondemarin IT WORKS! 

As you say, it should be updated on every deploy so adding that configuration to the yml would be perfect.

I'm also overwhelmed with work and I don't have any experience with CloudFormation but I can give it a try.

Thank you very much again.

**Comment by Mrt3383x38** [comment]
Binance kaldırdım indirdim eror veriyo
