### ISSUE TITLE
tenanTreeFrontend › Error: ENOENT: no such file or directory, open '.next/serverless/pages-manifest.json'

### ISSUE THREAD

**Issue by barrysteyn** [danielcondemarin/serverless-next.js#190]
Hi

Trying to use the new component. However, when I try deploy, I get this problem:

```tenanTreeFrontend › Error: ENOENT: no such file or directory, open '/.next/serverless/pages-manifest.json'```

Here is my folder structure:
```
@types
README.md
client
declarations.d.ts
next-env.d.ts
next.config.js
node_modules
package.json
pages
scripts
server
serverless.yml
static
tools
tsconfig.json
tslint.json
yarn.lock
```

**Comment by danielcondemarin** [comment]
@barrysteyn Strange. Looks like there is a build problem in your app. When the next app is built there should be a `/.next/serverless/pages-manifest.json` file. Are you building using `target: "serverless"` ? Also, can you share your serverless.yml next app bit and any other info you may think is relevant.

**Comment by barrysteyn** [comment]
>  Are you building using target: "serverless" ? Also, can you share your serverless.yml next app bit and any other info you may think is relevant.

No, I am trying to convert a project from the plugin to the component, and the plugin automatically makes the target serverless. I think for testing locally, we have left target as it's default.

**Comment by danielcondemarin** [comment]
Perhaps is best to add some validation in the component to make sure the `next.config.js` is set to `serverless`.

**Comment by barrysteyn** [comment]
> Perhaps is best to add some validation in the component to make sure the `next.config.js` is set to `serverless`.

Yes, this would be great. Maybe (as in the plugin version) it can just silently be inserted if not present. But an easier way would be just to add a documentation section explaining to people who are migrating that they need this present.

Great work Daniel, this is amazing.

**Comment by danielcondemarin** [comment]
> Great work Daniel, this is amazing.

Thanks Barry!

I've added a separate issue for the target validation work.  https://github.com/danielcondemarin/serverless-next.js/issues/194

**Comment by billzhong** [comment]
Hi, I had same issue, adding `{target: 'serverless'}` to `next.config.js` fixed. It will be great to add target validation.

**Comment by kartikag01** [comment]
I am also facing the same issue, as `.next` folder was not present so the error was coming on running  `serverless` command


```
  error:
  Error: pages-manifest not found. Check if `next.config.js` target is set to 'serverless'
    at CLI.renderError (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/Context.js:308:15)
    at Object.runComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:218:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  1s › myNextApp › pages-manifest not found. Check if `next.config.js` target is set to 'serverless'
```

serverless command should auto-generate `.next` folder

**Comment by billzhong** [comment]
I am having the same issue after update to 1.7.1
My workaround is run `next build` before serverless deploy.
