### ISSUE TITLE
Wrong debug message

### ISSUE THREAD

**Issue by skycremaschinin** [danielcondemarin/serverless-next.js#195]
**Describe the bug**
"Skipping nextjs build phase ..." message is shown while nextjs build phase is executed.

**To Reproduce**
1. don't set build: false in serverless.yml 
2. Run npx serverless -- debug
3. See error

looking into serverless.js, log command is misplaced:

`if (inputs.build !== false) {
      this.context.debug("Skipping nextjs build phase ...");
      await this.build(inputs);
    }`

should be
`if (inputs.build !== false) {
      await this.build(inputs);
    }else{
     this.context.debug("Skipping nextjs build phase ...");
}`

@danielcondemarin i could fix it, but maybe it take less for you.

**Comment by danielcondemarin** [comment]
@skycremaschinin That's been fixed / removed in the codebase, just need to release it now 👍

**Comment by skycremaschinin** [comment]
to fast to me! 🚀
