### ISSUE TITLE
Cookie and Query string forwarding

### ISSUE THREAD

**Issue by macs91** [danielcondemarin/serverless-next.js#200]
**Describe the bug**

Cloudfront default behavior setup by the component does not enable forwarding for cookies and query string, thereby making it impossible to handle business logic based on cookies like auth. I set those options from the AWS Console and everything works, but a new deploy overrides the behavior

**Expected behavior**
The component allows cookies and query string forward for the distribution default behavior

**Comment by macs91** [comment]
@danielcondemarin it's weird, because I read through the source code of the component and it seems that by default the default cache behavior should be set to allow cookies and query string forwarding. Even the json template produced under `.serverless` folder has default behaviour correctly set. Is this a bug in `@serverless/aws-cloudfront` component? 🤔

**Comment by danielcondemarin** [comment]
@macs91 It could be a bug in the `aws-cloudfront` component. 

@josephluck might be able to shed some light on this. I believe he worked on this previously.

**Comment by macs91** [comment]
@danielcondemarin I think I spotted the error.. Cloudfront accept the input like this:
<img width="418" alt="Screen Shot 2019-10-12 at 17 25 04" src="https://user-images.githubusercontent.com/4640135/66703696-813f0d80-ed15-11e9-8b5f-04fd91679574.png">
But in the code generated by serverless next js component the parent key `forward` is missing:
![Screen Shot 2019-10-12 at 17 25 25](https://user-images.githubusercontent.com/4640135/66703714-961ba100-ed15-11e9-83a1-bc5774817592.png)

Can you confirm?

**Comment by danielcondemarin** [comment]
@macs91 Good spot! Feel free to PR if you'd like 🙌

**Comment by macs91** [comment]
@danielcondemarin [contributing guide](https://github.com/danielcondemarin/serverless-next.js/blob/master/CONTRIBUTING.md) seems related to the serverless plugin, do you have more updated instructions on how to run and test this project?

**Comment by josephluck** [comment]
> @danielcondemarin I think I spotted the error..:

Great spot. I hadn't looked in to it yet, but really glad you've found the issue!

**Comment by macs91** [comment]
@danielcondemarin @josephluck I opened a PR https://github.com/danielcondemarin/serverless-next.js/pull/202

**Comment by danielcondemarin** [comment]
Closing folks, now published @1.4.1. Thanks @macs91 🙏
