### ISSUE TITLE
Next.js 9.1 public directory support

### ISSUE THREAD

**Issue by jayarnielsen** [danielcondemarin/serverless-next.js#207]
**Describe the bug**
As of next.js 9.1, the `static` directory should be placed inside of the `public` directory. https://nextjs.org/blog/next-9-1#public-directory-support

With the current serverless component, files in the `public/static/*` folder are unreachable because of the cloudfront rule for `static/*`.

**To Reproduce**
1. place static assets in `public/static`
2. deploy
3. try to access static asset at domain.tld/static

**Expected behavior**
Static asset resolves.

**Comment by Enalmada** [comment]
This would be good to prioritize as old Next users will be encouraged to migrate as console says `The static directory has been deprecated in favor of the public directory. https://err.sh/zeit/next.js/static-dir-deprecated` and new users to Next will put everything in the `public/static` directory.  Moving things to 'public/static' will work locally but not work using serverless-next.

**Comment by PrimeObjects** [comment]
Not sure whether it is the same issue, I have images in /public/images folder, it works file when run locally. After deploy to AWS. I can see a public folder in my S3, However /images/file.mp4 does not work.

**Comment by skycremaschinin** [comment]
opened PR #234 to solve this issue

**Comment by romainquellec** [comment]
Is it closed as the PR is accepted ?

**Comment by mikestopcontinues** [comment]
What's the status on this?

**Comment by aldrinc** [comment]
For folks landing here wondering about why images don't show up when placed in sub folders. I found that having any assets in sub folders under /public does not work when deployed. 

Unfortunately as a workaround I had to move out all my assets from sub folders like /public/images directly into /public so they could be accessed. If anyone knows a different workaround I'm all ears.

Additionally, new assets that are added to public folder don't automatically get the correct permissions when deployed. I have to manually update them as public in S3 so the assets (e.g. images) are visible in my application.

**Comment by danielcondemarin** [comment]
I have tested on the latest version of the project and this should work as expected. 

There is only one caveat, if you have both `static/` and `public/static` folders, only resources in `static/` will be found. I intend to completely remove support for `static/` in the next major version bump to avoid confusion. 

Could folks test and feedback using the latest version?

**Comment by danielcondemarin** [comment]
Closing this as it should be working as expected

**Comment by keisukekomeda** [comment]
I think the case "1" shown below is the only acceptable code.
I am wondering whether all the request for static image assets kick the lambda@Edge, or cloud front cache allows us to get image file without kick lambda@Edge?

1. Put image files in public dir, and jsx is like ```<img src="image.png">```.
In this case, both local environment and deployed environment work.

2. Put image files in public/static dir, and jsx is like ```<img src="public/static/image.png" />```.
In this case, deployed environment works, but local environment doesn't work.

3. Put image files in public/static dir, and jsx is like ```<img src="static/image.png" />```.
In this case, local environment works, but deployed environment doesn't work.

**Comment by stan-sack** [comment]
I don't think that `public/static/` works. To actually test this you need to go to your bucket and delete the residual `static` folder which will be left from previous deployments. I could also see that all the files were correctly uploaded to the `public/static/` folder however I'm getting a 403 from cloudfront. I invalidated my cloudfront cache just to be sure that wasnt the issue and I'm still getting a 403. This is using latest master.

Moving the files back to `/static` fixes the issue.

**Comment by malimccalla** [comment]
Im having an issue with this too. Locally files in `public/img` are being loaded but after building the project and dpeloying they are not working.

**Comment by joebanks10** [comment]
I noticed that removing the cloudfront behavior rule for the `static/*` path pattern fixes the issue. Is there a way to prevent this rule to be written @danielcondemarin ?

**Comment by danielcondemarin** [comment]
> I noticed that removing the cloudfront behavior rule for the `static/*` path pattern fixes the issue. Is there a way to prevent this rule to be written @danielcondemarin ?

There isn't a way right now to prevent it from being added. I am tempted to remove it completely but that would be a breaking change. I think is worth looking into how the Next.js server does this and do the same. Maybe if the static folder is present add the `static/*` cache behaviour otherwise don't.

**Comment by joebanks10** [comment]
That sounds good to me! Or a config option works too. For an immediate workaround, we're migrating static files to a new folder (e.g.`public/assets`) to avoid the conflict. Thanks!

**Comment by joekitaj** [comment]
I am still experiencing the subfolder issue as described above.

Everything works fine locally, but when depolyed, any files within `public/sub-folder` are not available (404)

**Comment by shabith** [comment]
Hey @joekitaj did you find a solution for the above problem?

**Comment by rapritchard** [comment]
@joekitaj @shabith 
Same question as above, I have a public/fonts folder that works fine locally but as soon as it goes up to my development server all the font files 404.

**Comment by yunjeongloper** [comment]
Any updates on this?

**Comment by pravinweb** [comment]
Hi,

I am facing same issue. Please find below details,

"next": "^9.2.0",
"@sls-next/serverless-component": "1.19.1-patch.1"

While running build it shows error - 
You cannot have assets in the directory [public/static] as they conflict with the static/* CloudFront cache behavior.

https://github.com/serverless-nextjs/serverless-next.js/blob/1d7a8eabd6e121154fb29b79423413cc1ff9ffdd/packages/libs/lambda-at-edge/src/build.ts#L662


My current project structure, is as per the NextJs recommendation here - https://github.com/vercel/next.js/blob/master/errors/static-dir-deprecated.md static assets should be placed as,

public/
  static/
    fonts/
    images/

To fix this do you recommend below structure?

public/
    fonts/
    images/


Do you have any other suggestions or alternative to fix this issue?

**Comment by danialfiaz** [comment]
Hi,

@rapritchard @pravinweb did you find any solution? I'm having the same issue.
I changed the directory structure but it still not working. Thank you

**Comment by rapritchard** [comment]
@danialfiaz I haven't worked with Next.js since August 2021 (left that job) so I have no idea if they ever found a solution and I haven't messed around with next in my own time since.
