### ISSUE TITLE
Dynamic Route Segments

### ISSUE THREAD

**Issue by hai98th** [danielcondemarin/serverless-next.js#212]
Hi folks. I have some problem when i deploy my app to production.

Given the following app:

pages/
├── [service]/
│  ├── [city]/
│  │  ├── index.js
│  │  ├── [district].js
├── profile/
│ └── [proid].js

When i run it in my localhost by: npm run dev or npm start. There is nothing wrong. 
following url:  localhost:3000/profile/my-pro-id/
 - build page: /profile/[proid].js
But when run on my production, i visit https://www.mydomainname.com/profile/my-pro-id  the _error page appears. It seem the build page now is  /[service]/[city].js with querry 
{
   service: profile,
   city: my-pro-id
}

What do I have to do now? many thanks!

**Comment by danielcondemarin** [comment]
Can you post the relevant code for the page? Also the Cloudwatch logs for the Lambda@Edge function in the region the error happened.

**Comment by hai98th** [comment]
Thank you, I have solved this problem

**Comment by danielcondemarin** [comment]
Out of curiosity what was the issue? I’m trying to improve how to better diagnose errors in the component

**Comment by hai98th** [comment]
I'm trying edit serverless.js in /home/.serverless/components/registry/npm/serverless-next.js@1.4.1/node_modules/serverless-next.js and it  succeeds. When i run "sls" command line. In .serverless_nextjs / default-lambda / manifest.json here:
{
  "pages": {
    "ssr": {
      "dynamic": {
        "/:slug": {
          "file": "pages/[slug].js",
          "regex": "^\\/([^\\/]+?)(?:\\/)?$"
        },
        "/:slug/:city": {
          "file": "pages/[slug]/[city].js",
          "regex": "^\\/([^\\/]+?)\\/([^\\/]+?)(?:\\/)?$"
        },
        "/:slug/:city/:district": {
          "file": "pages/[slug]/[city]/[district].js",
          "regex": "^\\/([^\\/]+?)\\/([^\\/]+?)\\/([^\\/]+?)(?:\\/)?$"
        },
        "/kh/:mid": {
          "file": "pages/kh/[mid].js",
          "regex": "^\\/kh\\/([^\\/]+?)(?:\\/)?$"
        },
        "/p/:proid": {
          "file": "pages/p/[proid].js",
          "regex": "^\\/p\\/([^\\/]+?)(?:\\/)?$"
        },
        "/test-service/:id": {
          "file": "pages/test-service/[id].js",
          "regex": "^\\/test-service\\/([^\\/]+?)(?:\\/)?$"
        }
      }, 

**something is wrong**, it must be: 
"/kh/:mid": {
          "file": "pages/kh/[mid].js",
          "regex": "^\\/kh\\/([^\\/]+?)(?:\\/)?$"
        },
        "/p/:proid": {
          "file": "pages/p/[proid].js",
          "regex": "^\\/p\\/([^\\/]+?)(?:\\/)?$"
        },
        "/test-service/:id": {
          "file": "pages/test-service/[id].js",
          "regex": "^\\/test-service\\/([^\\/]+?)(?:\\/)?$"
        },
        "/:slug": {
          "file": "pages/[slug].js",
          "regex": "^\\/([^\\/]+?)(?:\\/)?$"
        },
        "/:slug/:city": {
          "file": "pages/[slug]/[city].js",
          "regex": "^\\/([^\\/]+?)\\/([^\\/]+?)(?:\\/)?$"
        },
        "/:slug/:city/:district": {
          "file": "pages/[slug]/[city]/[district].js",
          "regex": "^\\/([^\\/]+?)\\/([^\\/]+?)\\/([^\\/]+?)(?:\\/)?$"
        }

because let's see your default-lambda-handler.js 

    for (route in dynamic) {
      const { file, regex } = dynamic[route];
      const re = new RegExp(regex, "i");
      const pathMatchesRoute = re.test(path);
      if (pathMatchesRoute) {
         return file;
       }
    }

if i go to the page: /p/le-kha-hai
the pathMatchesRoute = true when route = /:slug/:city

Thanks. I am new and sorry if I have not understood the problem yet

**Comment by danielcondemarin** [comment]
This sounds like a bug, surely /p/:proid should be matched before /:slug/:city

**Comment by pecoram** [comment]
Hi @danielcondemarin, can you tell me if this issue is already resolved or will be resolved soon?

**Comment by skycremaschinin** [comment]
hi @hai98th , how do you solved it?

**Comment by danielcondemarin** [comment]
Hi folks 👋 This should now be fixed in @1.6.0. Could someone test and confirm?

**Comment by pecoram** [comment]
Hi Daniel,
I confirm it is fixed! Thank you :)
