### ISSUE TITLE
Fully decouple next build from component 

### ISSUE THREAD

**Issue by danielcondemarin** [danielcondemarin/serverless-next.js#214]
**Is your feature request related to a problem? Please describe.**

Currently the next component takes on the responsibility of building the next app. Whilst this is "nice", it makes build issues harder to debug, reduces flexibility of different build workflows users have (especially in CI) and adds overhead to the component development for little value. 

**Describe the solution you'd like**

Fully decouple next build from the component deployment. To deploy users can do:

`next build && serverless`

If you have a custom build directory:

```yml
component: serverless-next.js
inputs:
  buildDir: /path/to/.next
```

To keep the zero config. nature of the component, default value of `buildDir` will be `./.next`. `buildDir` is the full path to the your `distDir` configured in [next.config.js](https://nextjs.org/docs#setting-a-custom-build-directory).

The `public` and `static` are expected to be siblings of `buildDir`.

**Additional context**

Solves issues https://github.com/danielcondemarin/serverless-next.js/issues/157, https://github.com/danielcondemarin/serverless-next.js/issues/149, https://github.com/danielcondemarin/serverless-next.js/issues/210

**Comment by jlaramie** [comment]
I've been thinking about this solution and while I like it it does remove the "0 configuration need" support. Maybe something like `inputs.buildNext: false` would skip the `next build` step but still do the other build steps like creating the manifests and lambda configuration.

**Comment by cameron-martin** [comment]
Regarding the build input, the README says:

> When true builds and deploys app, when false assume the app has been built and uses the .next .serverless_nextjs directories in nextConfigDir to deploy.

However, how do I generate the `.serverless_nextjs` folder?

**Comment by cameron-martin** [comment]
It seems that I should be able to invoke the [`build` method of the component](https://github.com/danielcondemarin/serverless-next.js/blob/476e52987d0a8c67920be77487042d12fdd12124/packages/serverless-nextjs-component/serverless.js#L24) using `serverless build`, according to the [components documentation](https://github.com/serverless/components#building-components):

```
  /*
   * Anything (Optional)
   * - If you want to ship your Component w/ extra functionality, put it in a method.
   * - You can run this function by running "$ serverless anything"
   */

  async anything(inputs = {}) {
    return {}
  }
```

However, this gives the error:

```
Error: "component" input is required to run custom methods
```

**Comment by cameron-martin** [comment]
Right, it just requires a `component` cli flag, as explained [here](https://github.com/serverless/components/issues/522).
