### ISSUE TITLE
local S3 buckets with serverless-offline

### ISSUE THREAD

**Issue by mdstaff** [danielcondemarin/serverless-next.js#22]
Hello, 

I really enjoy using your serverless plugin.  Would it be possible to setup local S3 image hosting with a plugin like https://github.com/ar90n/serverless-s3-local?

I'd be happy to help contribute to this repo towards that end.  Looking forward to your response.

**Comment by danielcondemarin** [comment]
@mdstaff Glad to hear you're enjoying using the plugin! 

> Would it be possible to setup local S3 image hosting with a plugin like https://github.com/ar90n/serverless-s3-local?

From a quick glance, I can't see why it wouldn't work, I've not tried `serverless-s3-local` myself but had a look at the src and seems to integrate with `serverless-offline` which is supported by this plugin.

Did you try using both plugins together in your serverless app?

**Comment by danielcondemarin** [comment]
Closing as this is stale now.

**Comment by mdstaff** [comment]
Hi Daniel, apologies for not responding, must have missed that email 🤦‍♂I'll take a look at this again early next week and reopen if needed.
