### ISSUE TITLE
Dynamic routes return 404 when using useRouter

### ISSUE THREAD

**Issue by SarKurd** [danielcondemarin/serverless-next.js#224]
**Describe the bug**
Dynamic routes return 404 when using useRouter hook instead of getInitialProps

**To Reproduce**
create a dynamic page

***doesn't work***
```js
//pages/posts/[id].js
import { useRouter } from "next/router";

const Post = () => {
  const router = useRouter();
  const { id } = router.query;

  return <p>Post: {id}</p>;
};

export default Post;

```
***works***
```js

const Post = ({ id }) => {
  return <p>Post: {id}</p>;
};

Post.getInitialProps = ({ query }) => {
  return { id: query.id };
};
export default Post;

```

**Expected behavior**
i expect to see the page loads with message `Post: :id`

**versions**

next: 9.1.2
serverless: 1.56.1
serverless-next.js: 1.4.1

**Screenshots**
<img width="1213" alt="Screenshot 2019-11-02 at 14 02 09" src="https://user-images.githubusercontent.com/13942717/68071294-6b06f900-fd79-11e9-9723-ce836c8e8f99.png">

**Comment by danielcondemarin** [comment]
@SarKurd I've pushed a fix for this in v1.6.0. Do you mind testing?

**Comment by danielcondemarin** [comment]
Closing this as it should now be fixed 👷 Feel free to re-open if you find any issues.

**Comment by SarKurd** [comment]
Thanks for the fix @danielcondemarin i will not have time to test it until the weekend.
