### ISSUE TITLE
Version Control?

### ISSUE THREAD

**Issue by ArronHsiao** [danielcondemarin/serverless-next.js#230]
Hi, I have used serverless-nextjs and found it's awesome! simple to use and quick deploy. The Question is that I'd like to have different versions deploying in the same time, say dev1.1, prod1.1 etc.. , but I found if I change project name in serverless.yml, I must delete the previous version( or it will say can't delete S3 bucket because not empty).  Is there any way to get basic version control feature?

**Comment by danielcondemarin** [comment]
@ArronHsiao This is a question for the [serverless component](https://github.com/serverless/components) project. 
Also, I believe [this example](https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component/examples/multiple-instance-environment) will help you achieve what you need
