### ISSUE TITLE
Nested Dynamic Route doesn't work.

### ISSUE THREAD

**Issue by zynkn** [danielcondemarin/serverless-next.js#235]
**Describe the bug**

My directory tree is

root
   - index.tsx
   - [id]
      - index.tsx
      - [uid].tsx
   - _error.tsx

**To Reproduce**
1. execute `sls` commend.
2. Files are generated in `/.serverless_nextjs`.
3. There's no files in `[id]` folder in `/.serverless_nextjs` even though I have `[id]/[uid].tsx`.
4. Also, I can't access `MYWEB.COM/RANDOM/ANOTHER`, I can see `_error.tsx` instead `[id]/[uid].tsx`

**Expected behavior**
I would like to access a nested dynamic route.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux ubuntu 19.10

**Comment by danielcondemarin** [comment]
@zynkn This is a genuine issue I’m working on fixing. Dynamic routes should also work without getInitialProps

**Comment by codeinaire** [comment]
I'm just checking if this is still being worked on? I'm using v1.9.3 and I'm having the same issue as @zynkn .
