### ISSUE TITLE
[Question components] how to use access SSM secrets?

### ISSUE THREAD

**Issue by SarKurd** [danielcondemarin/serverless-next.js#237]
We have a repo that use Serverless componnets, i can't find the docs to properly define environment variables outside the repo using components, i want to use SSM (or another thing) but can't find any guides.

Also a channel to ask silly question like that would be appreciated instead of using github issues :)

**Comment by danielcondemarin** [comment]
@SarKurd You could use a solution similar to the what the DynamoDB example does. i.e. talking to SSM in getInitialProps to read your secret variables. See the example how to do that here: https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/serverless-nextjs-component/examples/dynamodb-crud/pages/todos/list.js#L26.

PS: For environment variables you could also use `build.env` as described in https://github.com/danielcondemarin/serverless-next.js#inputs
