### ISSUE TITLE
nextjs component inputs

### ISSUE THREAD

**Issue by pontusab** [danielcondemarin/serverless-next.js#238]
I'm trying to add inputs like `memory: 2048` but that doesn't work, is this something that is supported un any way?

**Comment by pontusab** [comment]
Also, I want to whitelist `cloudfront-viewer-country` header, but if I add that to CloudFront and then redeploy it's gone again, is there a way to customize that from the component inputs too?

**Comment by andreyvital** [comment]
I have the same questions as above.

**Comment by pontusab** [comment]
I have a fork that I use, for now, I can do a PR next week

**Comment by danielcondemarin** [comment]
> I have a fork that I use, for now, I can do a PR next week

That would be much appreciated!
