### ISSUE TITLE
Images in public directory don't resolve

### ISSUE THREAD

**Issue by sushi30** [danielcondemarin/serverless-next.js#242]
**Describe the bug**
Images in `public` directory don't resolve properly.

**To Reproduce**
1. Clone repo
```
git clone https://github.com/sushi30/nextjs-serverless-public.git
cd nextjs-serverless-public
```
2. Install
```
npm install
```
3. deploy
```
serverless
```
4. logo.gif isn't resovled

**Expected behavior**
logo.gif should resolve

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 Education

**Comment by danielcondemarin** [comment]
@sushi30 You mind closing assuming your PR changes work?
