### ISSUE TITLE
multiple-instance-environment error

### ISSUE THREAD

**Issue by nodabladam** [danielcondemarin/serverless-next.js#246]
Running the [multiple-instance-environment example](https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component/examples/multiple-instance-environment) is giving me this error:

```
> env-cmd -e staging serverless --stage=staging

  error:
  TypeError: Cannot read property 'name' of undefined
    at new Component (\node_modules\@serverless\core\Component.js:6:17)
    at new Deploy (\serverless.js:6:1)
    at Object.runComponents (\node_modules\@serverless\cli\src\index.js:195:23)
    at Object.<anonymous> (\node_modules\serverless\bin\serverless.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

```
I feel like I got it working a week or two ago and am coming back to it now and getting this.  Can anyone using it confirm it is still working or suggest what might be causing this for me?

**Comment by barrysteyn** [comment]
The way I built the example, you don't need to use `env-cmd`. Can you reply to this with a dump of both your `serverless.yml` and `serverless.js` files?

**Comment by nodabladam** [comment]
Hey, 

Yes, I am just using env-cmd for unrelated nextjs-auth0 settings.  It seems like serverless is crashing before even getting into the async default function.  Thank you for your thoughts on what this might be!

serverless.yml
```
nodablFrontend:
  component: serverless-next.js
  inputs:
    bucketName: ${env.bucket}
```

serverless.yml (should be identical to example with exception of some logging the dotenv)
```
const { Component } = require("@serverless/core");

class Deploy extends Component {
  async default(inputs = {}) {
    const { stage } = inputs;
    if (stage === "staging" || stage === "prod") {

      const dotenv = require("dotenv");
      // Will load env-${stage} as environment variables
      const result = dotenv.config({ path: `${__dirname}/env-${stage}` });

      if (result.error) {
        throw result.error;
      }
      console.log(result); // eslint-disable-line no-console
      console.log("Running..."); // eslint-disable-line no-console
      const template = await this.load("@serverless/template", stage);
      const output = await template({ template: "serverless.yml" });
      return output;
    } else {
      this.context.log(
        "No environment defined... Choices are staging and prod!"
      );
    }
  }

  // Remove will allow the stage to be set on the command line
  // run like so: serverless remove --stage=staging
  async remove(inputs = {}) {
    const { stage } = inputs;
    if (stage === "staging" || stage === "prod") {
      const template = await this.load("@serverless/template", stage);
      const output = await template.remove();
      return output;
    }
  }
}

module.exports = Deploy;

```

env-stage (not referring to domain right now but here for completeness)
```
bucket=nodabl-frontend-nextjs-stage
domain=["next-stage", 'nodabl.co']

```

.env-cmdrc (stuff for [nextjs-auth0 module](https://github.com/auth0/nextjs-auth0#runtime-configuration))
```
  "staging": {
    "AUTH0_CLIENT_ID": "...",
    "AUTH0_DOMAIN": "dev.auth0.com",
    "AUTH0_CLIENT_SECRET": "...",
    "AUTH0_CLOCK_TOLERANCE": 20000,
    "AUTH0_AUDIENCE": "...",
    "REDIRECT_URI": "https://....cloudfront.net/api/callback",
    "POST_LOGOUT_REDIRECT_URI": "https://....cloudfront.net/",
    "SESSION_COOKIE_SECRET": "...",
    "NODE_ENV": "production"
  }
```

**Comment by barrysteyn** [comment]
Here are a few ideas:

 1. Are you calling your env `env-stage`? If so, that's incorrect, it should be `env-staging` or `env-prod`.
 2. Delete your state (`.serverless` folder) and try redeploy again.
 3. What version of `@serverless/core` do you have? Make sure it's the latest.

Let me know.

**Comment by nodabladam** [comment]
Thanks for your thoughts on this.  

env-stage was a typo in the comment above, sorry about that and fixed. 
I deleted the .serverless folder and same issue.
Lock file says I am using `@serverless/core`  2.0.25.  I tried on a few other projects that deployed successfully before and they are also all failing with the same error so I think it must be some @serverless dependency issue.

**Comment by nodabladam** [comment]
Update: Going down to these versions explicitly defined in the example actually makes it work: 
```
    "@serverless/core": "^1.1.2",
    "@serverless/template": "^1.1.3",
    "serverless": "^1.51.0"
```

**Comment by barrysteyn** [comment]
Ooooh, that's kinda bad. I will need to figure out what's going on with core. Let me ping them.

**Comment by barrysteyn** [comment]
Okay, so it seems that version of @serverless/core is not stable. The core maintainers are aloof, so I don't really know what their thinking is. Worse, it seems like version 2.X has been uploading to NPM locally - I can not find any reference to it on GitHub. I am actually very worried about the serverless components project. The maintainers have just gone radio silent with no explanation. I have been told that they are working hard and trying to make a major announcement in Dec, but their silence is deafening (forgive the English oxymoron to those whose first language is not English)

**Comment by barrysteyn** [comment]
This issue can be closed @danielcondemarin and @nodabladam. The core maintainer of serverless components released an unstable version (2.X) by mistake. See https://github.com/serverless/components/issues/529

**Comment by nodabladam** [comment]
Thanks for looking into this!
