### ISSUE TITLE
Custom routes

### ISSUE THREAD

**Issue by Xocix** [danielcondemarin/serverless-next.js#247]
**Is your feature request related to a problem? Please describe.**
For SEO reasons my routes need to be in a specific language, the react components are in English so this is a problem if i cannot change them to for example Swedish. I found this older issue with similar problem but that does not work: https://github.com/danielcondemarin/serverless-next.js/issues/98, looking at the documentation we cannot specify routes

**Describe the solution you'd like**
Next has a plugin called next-routes where you can specify routes like this: 
`
module.exports = routes()
    .add('home', '/hem', 'home')
    .add('about', '/om-oss', 'about')
`
If we can use this plugin it will solve this issue. 

Also i have checked the manifest.json file, if we can modify it somehow before deployment that could work too.

**Comment by danielcondemarin** [comment]
@Xocix This component uses next's public filesystem routing. 
I suggest you raise the issue in next's repo, right now this is outside of the scope of this project.
