### ISSUE TITLE
Error: "component" input is required to run custom methods

### ISSUE THREAD

**Issue by cinnabarhorse** [danielcondemarin/serverless-next.js#256]
Hi, this is probably a dumb question, but after installing this serverless component, I'm unable to run normal serverless methods like 'serverless --help' or 'serverless offline start' after installing serverless offline. 

I googled the error and found no results, so I'm wondering what this error means, and what workarounds there are for running serverless commands from the CLI when serverless-next.js is installed. Thanks.

Full CLI error:

 error:
  Error: "component" input is required to run custom methods
    at Proxy.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:350:13)
    at Object.runComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:209:40)

**Comment by adamthewan** [comment]
@cinnabarhorse how did you manage to solve it?

**Comment by cinnabarhorse** [comment]
I ended up separating the serverless.yml file used for the serverless component from the serverless.yml used for other things like cloud functions. 

So I have an app folder with a serverless.yml with serverless-nextjs, and a functions folder with a serverless.yml with the schema for cloud functions.

**Comment by cinnabarhorse** [comment]
@adamthewan 

I ended up separating the serverless.yml file used for the serverless component from the serverless.yml used for other things like cloud functions.

So I have an app folder with a serverless.yml with serverless-nextjs, and a functions folder with a serverless.yml with the schema for cloud functions.
