### ISSUE TITLE
 Error: Component "serverless-next.js" was not found on NPM nor could it be resolved locally.

### ISSUE THREAD

**Issue by seanliultron** [danielcondemarin/serverless-next.js#257]
**Describe the bug**
I followed the `Getting Started` section and installed serverless-next.js (1.7.0)
update my serveless.yml to be 
```
#serveless.yml 
name: test

myTest:
  component: serverless-next.js
```

**To Reproduce**
1. next build (with target: serverless)
2. serverless

**Expected behavior**
should deploy to aws for me

**Screenshots**
```
sean.li@NY web (serverless-demo) $ serverless

  error:
  Error: Component "serverless-next.js" was not found on NPM nor could it be resolved locally.
    at /Users/sean.li/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/@serverless/core/src/utils/download.js:99:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

  0s › Template › Error: Component "serverless-next.js" was not found on NPM nor could it be resolved locally.
```

**Desktop (please complete the following information):**
MacOS
Node 12.13.1

**Comment by danielcondemarin** [comment]
Strange, 1.7.0 is clearly on NPM. 

![image](https://user-images.githubusercontent.com/1122442/70561658-c3a09180-1b82-11ea-8f41-3f32b261027f.png)

**Comment by seanliultron** [comment]
> Strange, 1.7.0 is clearly on NPM.
> 
> ![image](https://user-images.githubusercontent.com/1122442/70561658-c3a09180-1b82-11ea-8f41-3f32b261027f.png)
> 
> Are you able to install the module directly from npm? `npm i serverless-next.js` ?

Yes.. i can install successfully. However, got the error when trying run serverless command.

**Comment by seanliultron** [comment]
found the issue. i have internal .npmrc set up. remove the local npm registry.
