### ISSUE TITLE
Environment variables missing from deployment in 1.7.1

### ISSUE THREAD

**Issue by stefl** [danielcondemarin/serverless-next.js#265]
I'm using this for [YearofColour.com](https://yearofcolour.com) (thanks!)

Until just now, environment variables for different stages were deploying as expected.

The 1.7.1 update went out between my last deployment and my most recent one, and all environment variables were no longer set.

Here is my serverless.js

    const { Component } = require("@serverless/core");

    class Deploy extends Component {
      async default(inputs = {}) {
        const { stage } = inputs;
        if (stage === "staging" || stage === "production" || stage === "beta") {
          // Will load env_${stage} as environment variables
          require("dotenv").config({ path: `${__dirname}/env_${stage}` });

          const template = await this.load("@serverless/template", stage);
          const output = await template({ template: "serverless.yml" });
          this.context.log(
            JSON.stringify(output)
          );
          return output;
        } else {
          this.context.log(
            "No environment defined... Choices are staging and prod"
          );
        }
      }

      async remove(inputs = {}) {
        const { stage } = inputs;
        if (stage === "staging" || stage === "production") {
          const template = await this.load("@serverless/template", stage);
          const output = await template.remove();
          return output;
        }
      }
    }

    module.exports = Deploy;`

And trying all combinations of the 'env' here produced no environment variables being set.

    nextApp:
      component: 'serverless-next.js'
      inputs:
        nextConfigDir: .
        #bucketName: year-of-colour-${env.stage}
        domain:
          - ${env.subdomain}
          - ${env.domain}
        INSTAGRAM_APP_ID: ${env.INSTAGRAM_APP_ID}
        INSTAGRAM_APP_SECRET: ${env.INSTAGRAM_APP_SECRET}
        INSTAGRAM_LEGACY_APP_ID: ${env.INSTAGRAM_LEGACY_APP_ID}
        INSTAGRAM_LEGACY_APP_SECRET: ${env.INSTAGRAM_LEGACY_APP_SECRET}
        GRAPHQL_ENDPOINT: ${env.GRAPHQL_ENDPOINT}
        GRAPHQL_API_KEY: ${env.GRAPHQL_API_KEY}
        REPORT_BUCKET_NAME: ${env.REPORT_BUCKET_NAME}
        LEGACY: ${env.LEGACY}
        env:
          host:
            domain: ${env.domain}
            subdomain: ${env.subdomain}
          INSTAGRAM_APP_ID: ${env.INSTAGRAM_APP_ID}
          INSTAGRAM_APP_SECRET: ${env.INSTAGRAM_APP_SECRET}
          INSTAGRAM_LEGACY_APP_ID: ${env.INSTAGRAM_LEGACY_APP_ID}
          INSTAGRAM_LEGACY_APP_SECRET: ${env.INSTAGRAM_LEGACY_APP_SECRET}
          GRAPHQL_ENDPOINT: ${env.GRAPHQL_ENDPOINT}
          GRAPHQL_API_KEY: ${env.GRAPHQL_API_KEY}
          REPORT_BUCKET_NAME: ${env.REPORT_BUCKET_NAME}
          LEGACY: ${env.LEGACY}
      env:
        host:
          domain: ${env.domain}
          subdomain: ${env.subdomain}
        INSTAGRAM_APP_ID: ${env.INSTAGRAM_APP_ID}
        INSTAGRAM_APP_SECRET: ${env.INSTAGRAM_APP_SECRET}
        INSTAGRAM_LEGACY_APP_ID: ${env.INSTAGRAM_LEGACY_APP_ID}
        INSTAGRAM_LEGACY_APP_SECRET: ${env.INSTAGRAM_LEGACY_APP_SECRET}
        GRAPHQL_ENDPOINT: ${env.GRAPHQL_ENDPOINT}
        GRAPHQL_API_KEY: ${env.GRAPHQL_API_KEY}
        REPORT_BUCKET_NAME: ${env.REPORT_BUCKET_NAME}
        LEGACY: ${env.LEGACY}

The solution for me was to pin to @1.7.0:

    nextApp:
      component: 'serverless-next.js@1.7.0'

**Comment by danielcondemarin** [comment]
@stefl For environment variables use `build.env` as per https://github.com/danielcondemarin/serverless-next.js#inputs
