### ISSUE TITLE
target: "serverless", and yet "pages-manifest not found."

### ISSUE THREAD

**Issue by mikestopcontinues** [danielcondemarin/serverless-next.js#266]
**Describe the bug**
When I try to deploy, I get this error:

> pages-manifest not found. Check if `next.config.js` target is set to 'serverless'

However, my target is "serverless" and the manifest is created at the right location (`.next/serverless/pages-manifest.json`).

Looking a little deeper, it seems the problem is the component isn't regenerating the next build. As in, if I delete `.next/` and run `serverless`, the directory isn't recreated. However, if I run `NODE_ENV=production next build && serverless`, I get a successful deploy.

**To Reproduce**
Just run `serverless` with the following config...

serverless.yml:
```yaml
app:
  component: serverless-next.js
  inputs:
    domain: ["subdomain", "example.com"]
```

next.config.js:
```js
module.exports = {
  target: 'serverless',
};
```

**Expected behavior**
I expect the component to handle the entire build process. Failing that, I expect the docs to describe the correct usage.

**Desktop (please complete the following information):**
```json
{
    "next": "9.1.6",
    "serverless": "1.60.1",
    "serverless-next.js": "1.7.0",
}
```

**Comment by danielcondemarin** [comment]
Can you confirm you're not using `1.7.1`? There have been a few reports of this issue and I believe it was introduced on the version I've published last night.

**Comment by mikestopcontinues** [comment]
I think this patch fixes the logic. And I had updated to `1.7.1`, then rolled back for debugging. I'm definitely seeing the issue on `1.7.0`. Confirmed in `node_modules` and `package-lock.json` and `which sls`.

**Comment by mikestopcontinues** [comment]
Actually, I just realized the version issue is connected with the caching in `.serverless/Template.json`. But when I tried deleting that dir, I got in trouble redeploying. Blergh.

**Comment by iDVB** [comment]
Also having this same error, although in my case, I'm using the AWS CDK Construct without sls components.

I'm trying to run things in separate directories and leverage the `Builder`'s config to point things around... and its running now, and starting to build the `.next` dir of files...
![image](https://user-images.githubusercontent.com/189506/110227812-035f4180-7eca-11eb-9e13-23bd9db42e2d.png)


However it err's our with...
`pages-manifest not found. Check if `next.config.js` target is set to 'serverless'`

**next.config.js**
```javascript
module.exports = {
  target: "serverless",
}
```

**/bin/cdk-nextjs.ts**
```javascript
...
const nextConfigDir = path.join(__dirname, '../dvb-next');
const outputDir = path.join(nextConfigDir, ".serverless_nextjs");
const builder = new Builder(nextConfigDir, outputDir,
  {
    cmd: './node_modules/.bin/next',
    cwd: '../dvb-next',
    env: {},
    args: ['build']
  });
...
```
