### ISSUE TITLE
How to Reduce server response times (TTFB) ?

### ISSUE THREAD

**Issue by kartikag01** [danielcondemarin/serverless-next.js#269]
**Describe the bug**
There are huge Reduce server response time (TTFB) on pages,  

![image](https://user-images.githubusercontent.com/10574227/71510655-94459080-28b5-11ea-8640-6736375b3662.png)

**To Reproduce**
1. Go to https://developers.google.com/speed/pagespeed/insights/
2. Run audit on-page, deployed by serverless
3. Check Opportunities section

**Expected behavior**
TTFB should not be that much.

**Comment by danielcondemarin** [comment]
@kartikag01 Can you provide an example repo to replicate this? On a basic next project backed with DynamoDB I'm getting consistent 100 score with TTFB under 1sec.

**Comment by kartikag01** [comment]
Yes, for the default application it's under 1sec,
when we keep adding stuff in it, these 2 errors comes into the picture.

This is url for trending gip repo, small code, just landing page. 
Demo: https://dyn4skf33ttva.cloudfront.net/  
Code : https://github.com/kartikag01/serverless-next-cloudfront-lambda

Which gives insights
![image](https://user-images.githubusercontent.com/10574227/71576260-13390400-2b16-11ea-9953-6425afb8519a.png)

So, these 2 things create big problem, when HTML goes bigger and application is a little complex.

In my production application, TTFB is around 2.5~3 Sec and Enable text compression is about ~1 sec.

Any idea or process by which it can be reduced.

**Comment by kartikag01** [comment]
The problem was with `Forward Cookies` in CloudFront config, setting it to None solved TTFB.

**Comment by barrysteyn** [comment]
@kartikag01 To note that by not forwarding the cookie, CloudFront is just better able to cache things. It is not so much as the setup is now magically working better, instead, the cache is now working better. However, you lose on the fact that two different with different cookies may get the same identical things served to them. If you are not using cookies, then okay. However, @danielcondemarin set this to forward everything on purpose as this behavior (at least for a SPA) is very rare.
