### ISSUE TITLE
Usage of environment variables inside of serverless.yml

### ISSUE THREAD

**Issue by doque** [danielcondemarin/serverless-next.js#278]
**Is your feature request related to a problem? Please describe.**
Using the "classic" serverless.yml with the serverless framework, I'm able to [define and use environment variables](https://serverless.com/framework/docs/providers/aws/guide/variables/#referencing-environment-variables), e.g. setting different URLs in a deployment pipeline:

```
# serverless.yml
my-app:
    component: serverless-next.js
    inputs:
        domain: ${env:URL}
```
However, this yields a yml parsing error when run:

```
Template › Deploying .
 DEBUG ─ Resolving the template's static variables.

  error:
  Error: invalid reference ${env:URL}
    at Object.<anonymous> (/.../node_modules/@serverless/template/utils.js:128:19)
```

**Describe the solution you'd like**
The ability to use injected environment variables inside the yml file. This is useful to target different stages (dev/qa/prd).

**Describe alternatives you've considered**
Having multiple .yml files in place (e.g. serverless.dev.yml) that are then renamed before running `serverless`. This is duplication and introduces unneeded complexity.

**Comment by danielcondemarin** [comment]
When using serverless-components use dot notation to access the env variables, e.g. `${env.URL}`. Docs: https://github.com/serverless/components#environment-variables

**Comment by jbhurruth** [comment]
Where is this documented? I can't see any mention of the dot notation on the linked page
