### ISSUE TITLE
{"message": "Internal server error"} after deploying nextjs app

### ISSUE THREAD

**Issue by antoinemaz** [danielcondemarin/serverless-next.js#291]
Hello,

i've an error when i deploy on AWS. For a "page" lambda function, we see this in the handler code :

const userHandler = require('./sls-next-build/account/register.html.js') 

but this file doesn't exist (in the lambda function), when i look the "sls-next-build" folder, in the sub directory "account", i just see these 2 files (for my "register" page) 

- register.html
- register.html.original.js

so, it's normal having this error message from CloudWatch :

"errorMessage": "Cannot find module './sls-next-build/account/register.html.js'",

So, all pages doesn"t work because of this non-existent file (.html.js)

i've followed the steps in the readme.

Thx :)

**Comment by IbrahimTareq** [comment]
@antoinemaz hi there, I'm having a similar issue and was wondering if you were able to resolve it 😄
