### ISSUE TITLE
Cloudfront configuration for custom lambda @ edge 

### ISSUE THREAD

**Issue by skycremaschinin** [danielcondemarin/serverless-next.js#297]
**Describe the bug**
i need to link a custom lambda @ edge to viewer-request event

**To Reproduce**
add following section (according to aws-cloudfront component) in serverless.yml
defaults:
      lambda@edge: # added to cloudfront default cache behavior
        viewer-request: arn:aws:lambda:us-east-1:123:function:myFunc:version

**Expected behavior**
Lambda @ edge is attached  to default behavior on viewer-request

**Comment by danielcondemarin** [comment]
@skycremaschinin May I ask why do you need to hook up to `viewer-request`?

**Comment by skycremaschinin** [comment]
@danielcondemarin it could be useful in many cases: for example, to redirect users to login page checking a session cookie, or some url rewrite.

Anyway, for the default behavior the origin request is hooked by routing lambda, so if i need to do something on request-side the viewer request is the only way.

**Comment by danielcondemarin** [comment]
I see what you mean now. Is something that potentially could be supported by https://github.com/danielcondemarin/serverless-next.js/pull/282

**Comment by skycremaschinin** [comment]
fine, with those feats your component would be customizable enough to be used in production envs.
hope #282 would be merged soon! thank you

**Comment by harryd31** [comment]
has this been merged yet? I really need to connect to the  viewer-response in our case

**Comment by danielcondemarin** [comment]
https://github.com/danielcondemarin/serverless-next.js/pull/282 has now been merged 🎉  Closing.
