### ISSUE TITLE
Lambda@edge functions aren't removed on 'sls remove'

### ISSUE THREAD

**Issue by lucas-varela** [danielcondemarin/serverless-next.js#300]
Is there a specific reason why lambda@edge functions are not deleted when using `sls remove`?

The remove method [doesn't load @serverles/aws-lambda](https://github.com/danielcondemarin/serverless-next.js/blob/e8b8b7e8b29867199932e5d133d1531148533cbd/packages/serverless-nextjs-component/serverless.js#L512), and the functions sit there wasting space if not manually removed.

I suspect that these functions can only be deleted after cloudfront completes their distribution removal process. If this is the case, the component should at least warn the user that these functions won't be removed for them, and I would be glad to PR this.

**Comment by danielcondemarin** [comment]
> I suspect that these functions can only be deleted after cloudfront completes their distribution removal process. If this is the case, the component should at least warn the user that these functions won't be removed for them, and I would be glad to PR this.

That's absolutely right, as of today is not viable to delete the edge functions because it takes too long, from the [docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-delete-replicas.html):

> You can delete a Lambda@Edge function only when the replicas of the function have been deleted by CloudFront.
> Replicas are typically deleted within a few hours.

I will happily take that PR to warn users 🙌

**Comment by lucas-varela** [comment]
Thanks for the explanation and the future PR 😃
