### ISSUE TITLE
Minimum required files need to be pushed to version control to preserve the app state?

### ISSUE THREAD

**Issue by SarKurd** [danielcondemarin/serverless-next.js#307]
I don't really want to push everything to version control as we have a pipeline to deploy to test environment on every push to master and on `tag` to prod and it will make the pipeline messy dealing with pushing everything back to version control after deployment and people may forget to push the state to version control if they deploy locally

What are the minimum required files in `.severless` folder that need to be pushed to version control to preserve the state? i don't mind longer build time

**Comment by barrysteyn** [comment]
`.serverless` is where state is stored. You can't really pick and choose. At least, if you do, you are opening yourself up to a lot of hassles and troubles.

**Comment by SarKurd** [comment]
How does the serverless-next.js checks if the Cloudfront distribution exists? isn't `_.json` the file?
