### ISSUE TITLE
RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation

### ISSUE THREAD

**Issue by ytwguru** [danielcondemarin/serverless-next.js#336]
**Describe the bug**
After running serverless build is interrupted by the error

```
...
DEBUG ─ Creating lambda qqk7ltu-ni97e9 in the us-east-1 region.
error:
  { RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation
```

**To Reproduce**
1. Run serverless --debug

**Expected behavior**
Should build and deploy the code

**Comment by danielcondemarin** [comment]
Duplicate of https://github.com/danielcondemarin/serverless-next.js/issues/336

**Comment by eenagy** [comment]
This issue cannot be duplicate of itself, it was mostly likely closed by mistake. Please reopen it. @danielcondemarin

**Comment by danielcondemarin** [comment]
Sorry! I actually meant a duplicate of https://github.com/danielcondemarin/serverless-next.js/issues/236
