### ISSUE TITLE
Scripts do not fail properly

### ISSUE THREAD

**Issue by mrowles** [danielcondemarin/serverless-next.js#337]
**Describe the bug**
A failed AWS command does not fail properly (meaning CI builds 'succeed' / fail silently

**To Reproduce**
1. Push any change which will fail due to AWS constraints e.g., CloudFront exists for CNAME
2. AWS Script will fail e.g., `error: CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.`
3. Script fails silently

**Expected behavior**
Script fails and with it, any CI build

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
Adding the following should catch a failed script:

```
#!/usr/bin/env bash

shopt -s failglob
set -eu -o pipefail

serverless
```

**Comment by danielcondemarin** [comment]
This is an issue in [serverless/components](https://github.com/serverless/components) not this project. Please raise in that repo 👍

**Comment by mrowles** [comment]
@danielcondemarin Done https://github.com/serverless/components/issues/566
