### ISSUE TITLE
Catch-all API routes excluded

### ISSUE THREAD

**Issue by markrawls** [danielcondemarin/serverless-next.js#351]
**Describe the bug**
Catch-all API routes are excluded, due to a bug in the outdated version of serverless components being used. The API route file should be included in the bundle. Instead, it is not and Cloudfront throws an HTTP 500 error.

**To Reproduce**
 - Create a new NextJS application
 - Use the README suggested serverless.yml
 - Create `pages/api/[...slug].js` in this app
 - Deploy it

**Expected behavior**
The API route file should be included in the bundle.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: (rolling release)

**Additional context**
I submitted a pull request to [@serverless/components](https://github.com/serverless/components) that got deployed and merged today, as well as a PR on [@serverless/serverless](https://github.com/serverless/serverless/pull/7550) that does the same thing for them. This should be fixed by updating to the latest serverless components libraries.

**Comment by dougturnkey** [comment]
Actually - is it possible that you are having a problem with dynamic next.js routes?...  for me pages/api/test.js works...  but pages/api/[collectionName]/find.js fails to resolve.

**Comment by markrawls** [comment]
It is in fact catch-all API routes, as I only have the one in the API folder. It may effect dynamic routes as well, but digging into the build files my catch-all route has been excluded.

**Comment by krish-dev** [comment]
I'm also facing the same kind of issue.

This is the directory listing generated at the time of deployment
![Screenshot 2020-04-14 at 8 25 11 AM](https://user-images.githubusercontent.com/7298557/79181344-cb6e8c00-7e29-11ea-99de-828eb80969c1.png)

And this is the directory listing exported from AWS Lambda console.
![Screenshot 2020-04-14 at 8 24 38 AM](https://user-images.githubusercontent.com/7298557/79181428-f6f17680-7e29-11ea-97bc-33bde1557e95.png)

**Comment by krish-dev** [comment]
Hi, @markrawls  I'm very new to the serverless world. I have a nextJS application with a catch-all route strategy. So, I'm facing the same issue, If you can please 🙏 give a step guide for a workaround until this bug gets fixed, So, that I can clone this repo and change the necessary configuration and point the serverless.yml component to the local repo. this will be really helpful and appreciable. Thanks

**Comment by markrawls** [comment]
Currently, there is no workaround to deploy your NextJS application with server less. Right now I am deploying them to Elastic Beanstalk

**Comment by danielcondemarin** [comment]
I'm just catching up on this. https://github.com/serverless/components/pull/577/files got merged which presumably fixes this issue but only for the new version of Serverless Components GA (which I'm working on at the moment).

Ideally we would get the older version of components patched as well with this fix so it unblocks people. (https://github.com/serverless-components/aws-lambda/pull/26 was meant to do this but now closed). @eslam Is it possible to patch the old version of components?

**Comment by danielcondemarin** [comment]
Thanks to @eslam for patching the old version of aws-lambda! This is now fixed in `serverless-next.js@1.11.1` 🎉
