### ISSUE TITLE
Can't find cloudwatch logging of api calls

### ISSUE THREAD

**Issue by dougturnkey** [danielcondemarin/serverless-next.js#352]
I am used to my serverless lambda functions console.logs showing up in the cloudwatch logs...  I'm not sure if this due to the regionless nature of this component? - but I don't know where to look for the logging (or how to configure it)

**Comment by mfbx9da4** [comment]
also can't find... did you find yours?

**Comment by ungarida** [comment]
It depends which region was hit by that call. You have to search in various region, for instance I'm in Italy and my calls are served by eu-central-1.
