### ISSUE TITLE
Create Cloudfront invalidation when using bucketName option

### ISSUE THREAD

**Issue by marklawlor** [danielcondemarin/serverless-next.js#354]
## Problem

When using the `bucketName` option, Cloudfront does not invalidate the cache forcing the user to create a manual invalidation.

## Possible solutions

Create a Cloudfront invalidation on all changed files

or

Create an option like `bucketPath: "random"` to deploy to a randomly generated path within the bucket and update the `Origin Path` on Cloudfront

**Comment by danielcondemarin** [comment]
An invalidation is being created now on every deployment. See https://github.com/danielcondemarin/serverless-next.js#static-pages-caching for details.
