### ISSUE TITLE
Error during deploy. no such file or directory

### ISSUE THREAD

**Issue by markkdev** [danielcondemarin/serverless-next.js#359]
**Describe the bug**
When trying to deploy my next app, I get an error 

Error: ENOENT: no such file or directory, stat '/Users/user/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js

Not sure when this started happening but it was working before.

I checked and the file does exist on my fs in that directory

**To Reproduce**
1. next build
2. serverless

**Expected behavior**
Serverless builds the next app and deploys it to aws

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Version [OSX 10.15.3]

**Additional context**
Not sure if this is related to any next updates or serverless updates.

**Comment by danielcondemarin** [comment]
This was very likely introduced in @1.9.9 which I released 20mins ago or so. I'll take a look now.

**Comment by markkdev** [comment]
Just saw that you published it. No worries, great work thank you

**Comment by kevinswarner** [comment]
I reverted to 1.9.8, but I still get the same error.

```
yarn remove serverless-next.js
yarn add serverless-next.js@1.9.8
sls
```

```
error:
  { [Error: ENOENT: no such file or directory, stat '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js' }

  7s › cowtinkerSignupApp › Error: ENOENT: no such file or directory, stat '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js'
```

**Comment by danielcondemarin** [comment]
> I reverted to 1.9.8, but I still get the same error.
> 
> ```
> yarn remove serverless-next.js
> yarn add serverless-next.js@1.9.8
> sls
> ```
> 
> ```
> error:
>   { [Error: ENOENT: no such file or directory, stat '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'stat',
>   path:
>    '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js' }
> 
>   7s › cowtinkerSignupApp › Error: ENOENT: no such file or directory, stat '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js'
> ```

Try fixing the version in your serverless.yml:

```
component: serverless-next.js@1.9.8
...
```

**Comment by danielcondemarin** [comment]
Hi folks, I've just released @1.9.10 with a fix. 
Could you test and close the issue assuming all goes well please?

**Comment by kevinswarner** [comment]
That fixed it for me. Thanks!

**Comment by danielcondemarin** [comment]
> That fixed it for me. Thanks!

Great stuff. I've deprecated `v1.9.9`
