### ISSUE TITLE
NextJS Target change support, Firestore build/deploy issue.

### ISSUE THREAD

**Issue by GuillaumeBecker** [danielcondemarin/serverless-next.js#363]
**Describe the bug**
NextJS seems to have dropped the support for the `target: serverless` to the profit of `target: 'experimental-serverless-trace'`. The current target isn't allowing to build and deploy when using Firestore.

**To Reproduce**
The situation is exactly as reported in this thread: https://github.com/zeit/next.js/issues/11860

**Expected behavior**
Change target to 'experimental-serverless-trace' ?

**Desktop (please complete the following information):**
OS: macOS 10.14.6 (Mojave)
- Version of Next.js: 9.3.4
- Version of Node.js: v12.14.2
- Version of Firebase: 7.14.0
- Version of Serverless: 1.67.3
- Version of Serverless-NextJS: 1.9.8

**Additional context**
This target still outputs the entrypoints in the format required for a serverless-type-platform, but requires to ship node_modules alongside it.

Thanks in advance!

**Comment by GuillaumeBecker** [comment]
Is there any update or work around for this issue ?

**Comment by uncvrd** [comment]
Hi @GuillaumeBecker I see you closed this issue, did you find a way to use `experimental-serverless-trace` with this library or did you just move on to a different solution? I'm dealing with the same problem :(

**Comment by TuuZzee** [comment]
Hi there @uncvrd. I am still using this on couple project currently. I can't recall exactly what fix the issue for me beside a package upgrade. Now the version I am using are the following:

```
"@sls-next/serverless-component": "^3.1.0",
"next": "^11.0.1",
"firebase": "^8.7.0",
"serverless": "^2.50.0",
```
I also still use `target: 'experimental-serverless-trace',` in the `next.config.js` file. Hope it helps :)
