### ISSUE TITLE
Blog link broken

### ISSUE THREAD

**Issue by lishine** [danielcondemarin/serverless-next.js#370]
It is the link to this repo at the start of the article
https://serverless.com/blog/serverless-nextjs/

**Comment by danielcondemarin** [comment]
Thank you for reporting! I've told the serverless framework folks and hopefully should be sorted soon.

**Comment by lishine** [comment]
Great work btw!
Because of this lib I can develop with nextjs-9 pages/API routes instead of adding a server and in time convert easily to edge-lambda!

**Comment by danielcondemarin** [comment]
Closing, I've added a temporary folder to the repo so the link still works, whilst the serverless folks update the blog.
