### ISSUE TITLE
Add possibility to use next.js fallback

### ISSUE THREAD

**Issue by baleksandr48** [danielcondemarin/serverless-next.js#371]
Nextjs has fallback feature. For example if you have blog with 1kk articles, you don't have to build static html for every article, you can set `fallback: true` in `getStaticPaths` and it will generate html for that article, return to user and save it with other static `html`s.

If I understand right - with `serverless-next.js` component we upload only those static file which were been generated during build and fallback-pages don't upload to other static pages.

Will you add this feature in the future?

**Comment by danielcondemarin** [comment]
> Will you add this feature in the future? 

Yep, I’ve already raised an RFC for this: https://github.com/danielcondemarin/serverless-next.js/issues/355

**Comment by Talhafayyaz11** [comment]
@danielcondemarin it would be great if you could guide me on this https://github.com/serverless-nextjs/serverless-next.js/issues/1317
