### ISSUE TITLE
How do I cache dynamic pages?

### ISSUE THREAD

**Issue by epicfaace** [danielcondemarin/serverless-next.js#373]
I'd like to cache dynamic pages from my cloudfront distribution with a TTL of 60 seconds. However, when I set the default ttl / minimum ttl to 60, I always get a "miss" from cloudflare when rendering the dynamic pages. How can I do this?

**Comment by danielcondemarin** [comment]
This is now possible to do by adding your own cache behaviours to CloudFront. Check https://github.com/danielcondemarin/serverless-next.js/blob/master/README.md#custom-cloudfront-configuration for more info!
