### ISSUE TITLE
S3 Upload not checking nextStaticDir

### ISSUE THREAD

**Issue by jlaramie** [danielcondemarin/serverless-next.js#386]
**Describe the bug**
feat(serverless-component): decouple uploading of next static assets to S3 from next component (#374) broke a feature I introduced which allowed specifying where the static directory lived. Broke by this commit 2b74304dd5d669caed399221e9cd7de0f4fbb0bc

**To Reproduce**
1. try and use nextStaticDir
2. nextStaticDir Doesn't get used and if no folder exists in nextConfigDir/static|public then no files will get uploaded

**Expected behavior**
nextStaticDir should be used when determining the parent folder of the "static" or "public" directory

nextStaticDir is needed because there are use cases where nextConfigDir does not contain the static directories as outlined in #259

**Comment by danielcondemarin** [comment]
@jlaramie Sorry about this! This needs some tests from preventing it happening again. Please if you have time could you PR a fix? 🙏

**Comment by jlaramie** [comment]
@danielcondemarin Yes I'm working the pull request right now. A test for this is a great idea as it took me a while to realize this was happening to my projects :(
