### ISSUE TITLE
Missing Cache-Control header on /public assets 

### ISSUE THREAD

**Issue by DanielOrtel** [danielcondemarin/serverless-next.js#392]
**Describe the bug**
Deployed with latest serverless-nextjs and checked my pagespeed results, and I'm seeing none of the public assets being cached(the last one is actually the recaptcha image from google, not one of my own): 
![PageSpeed_Insights](https://user-images.githubusercontent.com/19431728/81336354-dd062500-90b1-11ea-9810-866aab1e0f01.png) 

I've checked the S3 bucket, and Cache-Control is indeed missing from assets: 

![S3_Management_Console (1)](https://user-images.githubusercontent.com/19431728/81336759-92d17380-90b2-11ea-9899-a7ed4d5e1c05.png)

However, everything under `_next` is being correctly cached: 

![S3_Management_Console (2)](https://user-images.githubusercontent.com/19431728/81337140-3c186980-90b3-11ea-9fbb-ba8c6691ca3f.png)

**To Reproduce**
1. deploy app with at least one asset in /public
2. check the assets metadata in S3

**Expected behavior**
Public assets set the Cache-Control header. 

**Desktop (please complete the following information):**
 - OS: same thing from happens from local Mac and Ubuntu CI
 - Version: `serverless-next.js@^1.11.3`

**Comment by markkdev** [comment]
Having this issue as well.

**Comment by danielcondemarin** [comment]
Hi folks 👋 

I don't think we've ever had a cache control on `public/` assets. I think the optimal solution here would be to allow users to pass their own cache control for `public/`. For example:

```
component: serverless-next.js
inputs:
  publicDirCacheControl:
    regex: '*.(jpg|png)' # match images in the public or static folder
    value: "public, max-age=31536000"
```

Let me know if you want to take a stab at it and I'll happily guide you and review a PR 🙌

**Comment by DanielOrtel** [comment]
Oh, my bad, I thought based on this old issue #139 that this was the expected behavior, but apparently I misunderstood things. 

I have some other work I need to take care of, but I can try to take a stab at it during the weekend.

**Comment by danielcondemarin** [comment]
> I have some other work I need to take care of, but I can try to take a stab at it during the weekend.

Great! Let me know if you need any help / guidance
