### ISSUE TITLE
Some .js assets are not being compressed

### ISSUE THREAD

**Issue by lone-cloud** [danielcondemarin/serverless-next.js#393]
**Describe the bug**
I'm on the latest everything. Tried a couple of deploys 30 minutes ago with a fairly simple project. Chrome auditing tools are telling me that a lot of large .js files, as well as the page itself, are being served without compression.

**Expected behavior**
All .js assets should be compressed.

**Screenshots**
<img width="605" alt="1" src="https://user-images.githubusercontent.com/595980/81354941-be883580-9081-11ea-8751-6eb28f8e80cc.png">

**Comment by danielcondemarin** [comment]
Could you share your cloudfront distribution compression settings (you can grab them from the aws console) and also the file urls that are not being compressed please

**Comment by hoboman313** [comment]
The files are all from the *_next/static/chunks* directory:
https://d1wmsk5f1w320f.cloudfront.net/_next/static/chunks/eb8d877c86bf32638b771805672dc53733ba04f3.09ed8e5c1b99a3f42b52.js
https://d1wmsk5f1w320f.cloudfront.net/_next/static/chunks/commons.fc508143ea0d583ac5f7.js
https://d1wmsk5f1w320f.cloudfront.net/_next/static/chunks/framework.126679bf45d7d49475d8.js

As you can see, they're missing the `content-encoding: gzip` response header.

I have not touched any cloudfront settings. I see 4 behaviors total with the first 3 having "Compress Objects Automatically" enabled and the default one having it disabled.

<img width="668" alt="behavior" src="https://user-images.githubusercontent.com/595980/81355966-df9e5580-9084-11ea-9060-378c8b76911b.png">

**Comment by lone-cloud** [comment]
Tested again now and it fixed itself. The performance score is the high 90s ¯\_(ツ)_/¯
