### ISSUE TITLE
Use Cache-Control: immutable for files in /_next/static

### ISSUE THREAD

**Issue by aheimlich** [danielcondemarin/serverless-next.js#40]
Next.js's built in server adds a `Cache-Control: immutable` HTTP header to certain files within `/_next/static`. It would be cool if this plugin could do that as well. It would also be nice to have a config option that would apply `Cache-Control: immutable` to other files/directories within `/_next/static`.

Relevant code:

- [Cache-Control header](https://github.com/zeit/next.js/blob/ed1207f78a94cdeab47ff6ed530c4d532f26acb9/packages/next-server/server/next-server.ts#L153)
- [Which files get the header](https://github.com/zeit/next.js/blob/ed1207f78a94cdeab47ff6ed530c4d532f26acb9/packages/next-server/server/next-server.ts#L165)

**Comment by danielcondemarin** [comment]
@aheimlich This makes perfect sense! I would happily accept a PR for the first part (the next cached paths). 
As for the config option I'd prefer to leave that out for now and keep the plugin options to a minimum, and get the default behaviour first closer to next's built in server.

**Comment by danielcondemarin** [comment]
Closed by https://github.com/danielcondemarin/serverless-next.js/pull/144 🚀
