### ISSUE TITLE
Serverless deploy throws config not found error

### ISSUE THREAD

**Issue by nodermatt** [danielcondemarin/serverless-next.js#404]
**Describe the bug**
I followed the  [nextjs tutorial](https://www.serverless.com/learn/tutorial/deploying-nextjs-on-aws/) and couldn't deploy the app to AWS, the console showed an error "serverless config file was not found" (see more below)

**To Reproduce**
1. Create project 
```
serverless create --template-url https://github.com/serverless-components/website
```
2. install dependencies
```
npm i serverless-next.js -D
npm install
```
3. login to AWS with serverless
```
serverless login
```
4. Add .env file and .yaml and add serverless AWS user credentials
5. run serverless or serverless deploy

**Expected behavior**
The deployment should suceed

**Screenshots**
```
PS C:\Users\niod\sandbox\serverless-nextjs> serverless       

 Error: serverless config file was not found
    at loadVendorInstanceConfig (C:\snapshot\serverless\node_modules\@serverless\components\src\cli\commands\utils.js:164:11)
    at Object.run (C:\snapshot\serverless\node_modules\@serverless\components\src\cli\commands\run.js:32:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at internal/main/run_main_module.js:18:47
    at Object.<anonymous> (C:\snapshot\serverless\node_modules\@serverless\components\src\cli\index.js:110:7)

0s » Serverless » serverless config file was not found
```

**Desktop (please complete the following information):**
 - OS: Win
 - Version 10

**Additional context**
I used serverless yesterday with other tutorials which worked fine. The main difference is then I used the "serverless create --template aws-nodejs" command. I didn't see a next.js template though which is why I'm not sure how to proceed.

Thanks for any hints.

**Comment by danielcondemarin** [comment]
Hi @nodermatt I suspect this is version 2 of serverless components which still isn't supported, that's currently being worked on. Could you post your `serverless.yml`?

**Comment by danielcondemarin** [comment]
> Hi @nodermatt I suspect this is version 2 of serverless components which still isn't supported, that's currently being worked on. Could you post your `serverless.yml`?

Yep just confirmed this is the case. Follow https://github.com/danielcondemarin/serverless-next.js/issues/380 for updates on when V2 will be supported. 

Also just make sure you're `serverless.yml ` has the following structure:

```
yourAppName:
  component: serverless-next.js@version_here
  inputs:
    ...
```

That should automatically opt you in V1 and not V2. The subtle difference between components V1 and V2 is the `yourAppName` part is missing in V2 yamls.
