### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '.next/prerender-manifest.json'

### ISSUE THREAD

**Issue by hnprashanth** [danielcondemarin/serverless-next.js#406]
**Describe the bug**
New alpha push breaks the deployment with error - [Error: ENOENT: no such file or directory, stat '.next/prerender-manifest.json']

**To Reproduce**
This problem started ever since 1.12.0-alpha.2 was published 

**Additional context**
If anyone faces this issue, make sure you pin the component version to stable version - 1.11.5

`component: serverless-next.js@1.11.5`

**Comment by danielcondemarin** [comment]
@hnprashanth What version of next.js are you using?

**Comment by hnprashanth** [comment]
@danielcondemarin 9.0.8

**Comment by danielcondemarin** [comment]
@hnprashanth Could you try updating to next `9.3.0` or greater?

**Comment by mcxolani** [comment]
also just started happening on my project without any upgrades or new installs

**Comment by danielcondemarin** [comment]
@mcxolani if you don’t pin a version number for serverless-next.js in your version yaml serverless will pull whatever is latest published on NPM. Check the installation on the README page which recommends pinning a version number.

Also this issue would only happen if you’re using next.js under 9.3.0

**Comment by mcxolani** [comment]
@danielcondemarin works fine, thanks

**Comment by danielcondemarin** [comment]
Closing this as it should work fine on Next 9.3.0 or above.
