### ISSUE TITLE
Forwarding "Host" header breaks static-pages

### ISSUE THREAD

**Issue by stan-sack** [danielcondemarin/serverless-next.js#408]
I've just started forwarding the `Host` header through CloudFront because I want my pages to know their own domain when they are being rendered on the server. I've found that this causes pre-rendered pages behind `static-pages/...` to break because the request now has an invalid signature due to the host header being changed.

I was able to fix this by explicitly setting the header in the default-handler as seen in [this AWS example](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-content-based-S3-origin-based-on-query):

```
    if (isHTMLPage) {
      request.uri = uri + ".html";
    }
```

is now

```
    if (isHTMLPage) {
      request.headers["host"] = [{ key: "host", value: s3Origin.domainName }];
      request.uri = uri + ".html";
    }
```

This will be fixable by the custom lambda handler when it is eventually implemented, or you might want to add this line. I'm not sure. I've just opened this to track the issue.

**Comment by danielcondemarin** [comment]
Good catch @stan-sack. I'm pretty sure is safe (probably best) to manually set the header when forwarding to S3. Feel free to PR 🙏 and I'll get it reviewed and merged ASAP.

**Comment by danielcondemarin** [comment]
Solved in https://github.com/danielcondemarin/serverless-next.js/pull/412
