### ISSUE TITLE
I'm hitting typescript errors when running serverless-next.js but not when I run locally

### ISSUE THREAD

**Issue by quietgopher** [danielcondemarin/serverless-next.js#414]
**Describe the bug**
When developing locally using nextjs (running the UI and also eslint), my build works fine.  When I run serverless, I hit different type errors.  I have a tsconfig.json and have some .eslintrc rules.

**To Reproduce**
I'm fine sharing more if needed.  I'm guessing there is a simple configuration issue I'm missing to get this to work properly.

# serverless.yaml
```
myUi:
  component: serverless-next.js
```

**Expected behavior**
I'd expect serverless-next.js to reuse my other configs by default.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Version 10.15.2

**Comment by danielcondemarin** [comment]
@quietgopher What error are you seeing? What's your directory structure, tsconfig.json etc.? If you could provide a repro that would be far easier for me to look into.

**Comment by danielcondemarin** [comment]
I'm closing, feel free to reopen if you are still having this issue and please provide the info above.
