### ISSUE TITLE
How to apply lambda layer

### ISSUE THREAD

**Issue by teajoon** [danielcondemarin/serverless-next.js#416]
I am finding a way to seperate the api lambda files.
Since the api file size is over 69905067 bites, it cannot be deployed now, even though i used prune, the size is over 69905067 bites.

Is there anyone who can tell me how to apply the lambda layer in serverless-next.js?

**Comment by danielcondemarin** [comment]
@teajoon Lambda layers are not supported in Lambda@Edge as of today. However, there is some ongoing work to dramatically reduce the size of the artefact being deployed. See https://github.com/danielcondemarin/serverless-next.js/issues/236 for more details.
