### ISSUE TITLE
Host header is set to s3 bucket on some dynamic pages

### ISSUE THREAD

**Issue by stan-sack** [danielcondemarin/serverless-next.js#434]
**Describe the bug**
I'm logging the the next.js request context and seeing the host header is being set to my S3 bucket: `host: '<my-static-bucket>.s3.amazonaws.com',`. This is in the cloudwatch logs which means that the header is being overridden for some dynamic pages. I've been trying to debug it but I can't tell for sure yet where the bug is. This doesn't happen for all pages.

**Expected behavior**
Host header should be `host: '<my-domain>.com`

**Additional context**
Im on version `1.12.0-alpha.8`

**Comment by stan-sack** [comment]
Ive just confirmed that the host is not being overridden with `addS3HostHeader`. It looks like the s3 host is set in the event payload. Do we have control over that?

**Comment by danielcondemarin** [comment]
@stan-sack That seems like intended behaviour from https://github.com/danielcondemarin/serverless-next.js/pull/412/files. 
I'd be very surprised if the host is set to S3's domain in the event payload. Could you add a bit more details of your findings? logs etc.

**Comment by stan-sack** [comment]
The intention of my PR was to have this behaviour when the page is served from S3. I dont think we should have the S3 header when we're hitting the lambda. It should just be the host header that we're getting from cloudfront.

**Comment by stan-sack** [comment]
I'm logging the event payload and i think it is:

`console.log(event.Records[0].cf.request.headers["host"]);` gave the following output:
`[ { key: 'Host', value: '<static-s3-bucket>.s3.amazonaws.com' } ]`

**Comment by stan-sack** [comment]
Ah I got it. Its because the default cloudfront behaviour is not merged with any that your pass in. I had the following:
```
        cloudfront:
            defaults:
                viewerProtocolPolicy: redirect-to-https
                compress: true
                forward:
                    headers:
                        [
                            "x-forwarded-host",
                            "x-forwarded-proto",
                            "origin",
                            "host",
                        ]
            test*:
                compress: true
                viewerProtocolPolicy: redirect-to-https
                ttl: 0
                forward:
                    cookies: "all"
                    queryString: false
```

and the behaviour I described is a result of the `host` header not being forwarded on `/test`. 

Sorry for the hassles. I'm literally the one person that shouldn't be asking about this lol.
