### ISSUE TITLE
Error page served when navigating to `/index.html` route

### ISSUE THREAD

**Issue by owain-stratton** [danielcondemarin/serverless-next.js#438]
**Describe the bug**
The served site from AWS no longer trims `/index.html` from the domain as it used to, and is now returning `_error.js`. Previously I didn't experience this issue and the `/index.html` route would be replaced with the root domain. 

**To Reproduce**
1. Go to https://d14obvdd2huy34.cloudfront.net
2. see the `crna` default landing page
3. Go to https://d14obvdd2huy34.cloudfront.net/index.html
4. see the `crna` default error page

**Expected behavior**
Go to https://d14obvdd2huy34.cloudfront.net/index.html and `index.html` is replaced

**Desktop (please complete the following information):**
 - Version 1.13.0

**Repro**
https://github.com/hartstrattoncreative/next-serverless-repro

**Comment by lone-cloud** [comment]
Note that as of the latest alpha, the 404.html page will be returned instead.
What you're suggesting is a relatively simple change to this loop in the default-lambda router: https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/lambda-at-edge/src/default-handler.ts#L49
I'm not convinced that this is a needed change and I don't see many sites work this way (ex. github, youtube).

**Comment by owain-stratton** [comment]
Ah ok, was there a reason the change was introduced that broke this? No I agree, it doesn't feel standard as you say those sites return `404` errors for `/index.html`. However this was working and is now not.

**Comment by danielcondemarin** [comment]
> Ah ok, was there a reason the change was introduced that broke this? No I agree, it doesn't feel standard as you say those sites return `404` errors for `/index.html`. However this was working and is now not.  

@owain-stratton It was unintended for that to work and untested. Also in terms of routing is important this project behaves in the same way the next server does, which returns a 404 for /index.html
