### ISSUE TITLE
404 errors don't get rendered correctly by the api-lambda

### ISSUE THREAD

**Issue by lone-cloud** [danielcondemarin/serverless-next.js#446]
404s don't get rendered correctly for API routes. This is supposed to be handled by the _error.js, but that returns 502 for me with a CloudWatch message from cloudfront: "ERROR Validation error: The Lambda function returned an invalid json output, parsed json should be an object type." 

^ Actually to get to that point took a workaround. You would normally see a 503 for 404'ed /api routes (in serverless trace mode) with a "Cannot find module 'next/dist/next-server/server/render" CloudWatch error message. This happens because buildApiLambda() is missing _error.js in its page list prior to calling nodeFileTrace. This causes that page's dependencies to not get bundled correctly. A simple `apiPages.push(path.join(this.serverlessDir, "pages/_error.js"));` there can fix it there to get to the 502 final boss that I'm currently working through.

Ideally, the api-lambda should return the static 404.html for all not-found routes.

**Comment by danielcondemarin** [comment]
Yeah just replicated this. 

> Ideally, the api-lambda should return the static 404.html for all not-found routes.
I disagree with that point. I think it should return a statusCode: 404 maybe with an empty JSON object. vercel seems to return a `code`and a `message`: https://vercel.com/api/123/456

**Comment by lone-cloud** [comment]
OK, makes sense. Shouldn't be hard to do. I can put out a PR for this later.
