### ISSUE TITLE
pages-manifest not found. Check if `next.config.js` target is set to 'serverless

### ISSUE THREAD

**Issue by lukemarshdv** [danielcondemarin/serverless-next.js#447]
I know this issue has been closed a couple of times but I've run through the steps to fix and I'm still having the same issues. Any help would be really appreciated!

I'm running the `serverless` command in AWS codebuild and I have `target: "serverless"` as stated in the docs. This is the error I'm seeing:
`pages-manifest not found. Check if `next.config.js` target is set to 'serverless`

I've listed the files in the `.next/serverless` folder and I can see:
```
init-server.js
on-error-server.js
pages
pages-manifest.json
``` 

This is my serverless file:
```
nextApp:
  component: serverless-next.js@1.10.0
```

I have both serverless and serverless-next.js packages installed:
```
"serverless": "^1.61.1",
"serverless-next.js": "^1.10.0",
```

**Comment by danielcondemarin** [comment]
@lukemarshdv Could you try using `@1.14.0` please?

**Comment by lukemarshdv** [comment]
@danielcondemarin Thank you so much for responding so quickly!
I'm still getting the same issue as before but I can give you some more information that might be of some use:

The deploy works on my machine when I run it and it took around 10 mins on first deploy

**Comment by danielcondemarin** [comment]
> The deploy works on my machine when I run it and it took around 10 mins on first deploy (There are many pages). AWS codebuild appears to be the problem

If you have many pages and your build takes long could you try `useServerlessTraceTarget` from https://github.com/danielcondemarin/serverless-next.js#inputs. .It's a new build target I'm working on, I'm interested to see how it compares. 

In terms of Codebuild what error do you get there?

**Comment by lukemarshdv** [comment]
I will try that first thing in the morning and let you know the results. Thanks again!

**Comment by lukemarshdv** [comment]
@danielcondemarin I tried it just now and I get the same error. Local build on my machine took ~90 seconds this time though which is an improvement

**Comment by danielcondemarin** [comment]
Could you try putting a simple repro I can take a look at? I appreciate you have a large app. but having a way for me to reproduce the issue will speed things up.

**Comment by lukemarshdv** [comment]
I think I may be out of my depth creating a simple repro here!

The setup that's being used is Github/Travis/Terraform/AWS CodeBuild and it might take me quite a while to set all those things up for you to be able to reproduce the issue!

**Comment by lukemarshdv** [comment]
Hi @danielcondemarin I have managed to deploy finally! This was the config setting I used:

```
nextApp:
  component: serverless-next.js@1.14.0
  inputs:
    build:
      cmd: node_modules/next/dist/bin/next
```

**Comment by danielcondemarin** [comment]
> Hi @danielcondemarin I have managed to deploy finally! This was the config setting I used:
> 
> 
> 
> ```
> 
> nextApp:
> 
>   component: serverless-next.js@1.14.0
> 
>   inputs:
> 
>     build:
> 
>       cmd: node_modules/next/dist/bin/next
> 
> ```

Great 👍🏻 I’ll be closing this then.
