### ISSUE TITLE
feature: allow definining env variables to be set on each lambda

### ISSUE THREAD

**Issue by lone-cloud** [danielcondemarin/serverless-next.js#453]
The goal of this feature is to ease the continuous deployment process by allowing the secret values to be set as environment variables per lambda. This will allow the component's users to not have to rely on building the env variables (stored in .env files) into the app bundle which may encourage storing API secrets in repos.

Example:

Secret keys are set to environment variables TOP_SECRET_KEY1 and TOP_SECRET_KEY2 respectively.

*serverless.yml*
```
myComponent:
  component: serverless-next.js@1.14.0
  env:
    defaultLambda: {
      MY_SECRET: ${env.TOP_SECRET_KEY1}
    }
    apiLambda: {
      API_SECRET: ${env.TOP_SECRET_KEY2}
    }
```

The MY_SECRET and API_SECRET env vars will now be set per lambda and will not need to exist in an .env file.
The implementation should handle the `env: {...}` case to set for both lambdas.
Should be a copy/paste implementation of the existing description/memory/name inputs.

@danielcondemarin Sounds good?

**Comment by lone-cloud** [comment]
As I look into it further, I believe build.env was used to provide this functionality in the past. Do envs get built into your bundle if you provide them in the next.config.js? This is not the recommended way to handle things anymore according the docs.

**Comment by danielcondemarin** [comment]
@lone-cloud Unfortunately Lambda@Edge does not support environment variables. This will probably change in future as AWS should add support for it at some point. 

> As I look into it further, I believe build.env was used to provide this functionality in the past. Do envs get built into your bundle if you provide them in the next.config.js? I don't believe this is the way to define env vars in the latest versions of Next.js and it's no longer listed in the docs.

That's exactly the case. That's why we added support for build-time Next.js env. configuration using `build.env`. 

There may be some work to be done to better support the next 9.4 env release using `dotenv` but not sure what that would look like right now.

**Comment by lone-cloud** [comment]
Very interesting. I did not realize that was a limitation.

I think the best course of action now is to have more documentation in the README to outline the next.config.js requirement as it is no longer standard. Next 9.4 revamped the way that env variables (https://nextjs.org/blog/next-9-4#new-environment-variables-support) should be provided and this was a big source of confusion for me when integrating with this component.
