### ISSUE TITLE
Getting a constant error, "cannot delete lambda function, because it is replicated"

### ISSUE THREAD

**Issue by DanielOrtel** [danielcondemarin/serverless-next.js#456]
**Describe the bug**
So far, when setting `name:defaultLambda`, nothing happened, so the function name was assigned the default value of random numbers. This appears to have been fixed in a recent version, so newer deploys name the function appropriately, but now the deploy process tries to delete the replicated functions directly, which it cannot do, due to the way aws sets up replicated functions, so it errors out and `InvalidParameterValueException: Lambda was unable to delete arn:aws:lambda:us-east-1[...] because it is a replicated function`. 

Addendum: **I'm also seeing some very weird behavior, where the site randomly loads old/new versions.**

Addendum 2: This appears to be because the actual deploy failed, when it couldn't delete the old functions, but the S3 assets were uploaded. 

**To Reproduce**
1. Deploy a next app with an older version of the package. 
2. Upgrade to the latest version and set `name:defaultLambda` to something. 
3. Deploy again.
4. Error should be showing.

**Expected behavior**
Older replicas are either cleaned up correctly, or not touched at all and left up to the user to handle. 

**Screenshots**

**Desktop (please complete the following information):**
 - N/A
 - serverless-nextjs: 1.12.0

**Comment by DanielOrtel** [comment]
Temporarily addressed this by removing `name:defaultLambda` and deleting the named functions. But this should still be addressed.

**Comment by lone-cloud** [comment]
You're actually running the latest alpha that was released earlier today if you're experiencing this error. 
The latest version of the aws-lambda component (that we're not using yet) requires manual deletion on renames too: https://github.com/serverless-components/aws-lambda/blob/master/src/serverless.js#L49
I'm not sure how to improve this experience.

**Comment by DanielOrtel** [comment]
The issue isn't really that it requires manual deletion, it's that it doesn't properly register the new function to the cloudfront distribution, so the whole deploy fails halfway. 

And regarding my versioning: I'm not sure what is going on with this package, but my yarn.lock, is specifically 1.12.0: 

```
serverless-next.js@^1.12.0:
  version "1.12.0"
  resolved "https://registry.yarnpkg.com/serverless-next.js/-/serverless-next.js-1.12.0.tgz#82d81fcea4f0b25271b6339f2590981103550b35"
  integrity sha512-JafMzpMgO7cRq5gDbprG7YZAyvz6Xqs6UHlUoduwVnOaWs7sLG6RIYiEKBMzA8JxSPk4h4DNjU8UzWoIdHbNyw==
  dependencies:
    "@serverless/aws-cloudfront" "^5.0.0"
    "@serverless/aws-lambda" "^3.0.3"
    "@serverless/aws-s3" "^4.2.0"
    "@serverless/core" "^1.0.0"
    "@serverless/domain" "^6.1.0"
    "@sls-next/lambda-at-edge" "^1.2.0"
    "@sls-next/s3-static-assets" "^1.1.0"
    fs-extra "^8.1.0"
    next-aws-cloudfront "^1.2.0"
```

Seeing the same thing in the actual package in the `node_modules` folder. This isn't the first time, when the package resolved to something other than what it's supposed to be either. Previously, a simple `yarn add serverless-next.js` installed a version greater than what was available, something like `^1.8.5`, when the latest, atm, is the `1.15.0-alpha.0`.

**Comment by lone-cloud** [comment]
Yeah, the version that you define in your package.json is not what gets used by serverless. Feel free to refer to the readme.

**Comment by DanielOrtel** [comment]
OOh, right, I forgot about that, I need to set the version in the serverless.yml.

**Comment by DanielOrtel** [comment]
Closing this, since it was an accidental usage of an alpha build.
