### ISSUE TITLE
Cookies shouldn't be forwarded for static files 

### ISSUE THREAD

**Issue by katspaugh** [danielcondemarin/serverless-next.js#459]
_Edit_: I'm completely rewriting the original issue.

Static file routes on CloudFront get created with the Query String and Cookies being forwarded to the S3 origin. This renders caching inefficient. Let's change it to not forward anything. I'd be happy to send a PR if you point me to where the config is in the code.

**Comment by danielcondemarin** [comment]
@katspaugh Could you pin a version number as recommended in https://github.com/danielcondemarin/serverless-next.js#getting-started? That will make sure is not up to serverless which version of the component to pick. Try using `@1.14.0` which is latest stable published.

**Comment by katspaugh** [comment]
Thanks! I did but it didn't help. Serverless was previously picking the 1.15.0-alpha.0.

**Comment by katspaugh** [comment]
I've compared the [CloudFront.yml](https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/serverless-plugin/resources/cloudfront.yml#L54) in this project and an [example template from AWS docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-cloudfront.html), and it's seems correct.
Something must be changing this config in the code?

**Comment by medv** [comment]
@katspaugh that example is from the serverless-plugin, which is different to serverless-next.js component.
This might help? https://github.com/danielcondemarin/serverless-next.js#custom-cloudfront-configuration

**Comment by katspaugh** [comment]
I see. To clarify, I'm arguing that cookies shouldn't be forwarded in the default configuration.

**Comment by lone-cloud** [comment]
I'm pretty confident that you're looking to make is here: https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/serverless-component/serverless.js#L231
It sounds like you want to add:
```
forward:
        headers: 'none
        cookies: 'none'
        queryString: false
```

**Comment by katspaugh** [comment]
Thank you, @lone-cloud!
