### ISSUE TITLE
Is there any way to remove `www` as the default subdomain, or have a redirect policy when accessing the root domain? 

### ISSUE THREAD

**Issue by DanielOrtel** [danielcondemarin/serverless-next.js#463]
**Is your feature request related to a problem? Please describe.**
We're recently had a weird issue, both with CORS and with user login on our site(example.com for this example). The issue came from the fact that our site is normally accessible as `https://example.com` and no redirects happen, but when someone tries to access as either `http://example.com` or `www.example.com`, they gets redirected to `https://www.example.com`.

Seeing as `www` is technically a different subdomain, users lose their login information/session and our CORS policy was only checking for the root domain, and not the `www` subdomain. CORS is pretty easy to fix, but users getting logged out is not. 

**Describe the solution you'd like**
One of two: 
- All users accessing `https://example.com` are redirected to `https://www.example.com`, everything else stays the same. 
- All users accessing `http://example.com` or `www.example.com` are redirected to `https://example.com`. 

**Describe alternatives you've considered**
Manually configuring the redirect behavior in AWS

**Additional context**
N/A

**Comment by lone-cloud** [comment]
I see that this feature has been requested multiple times now. Ex. #192
I'll close and address this in the solution for #465
